### ISSUE TITLE
simple-date interval oddities

### ISSUE THREAD

**Issue by slyrus** [marijnh/Postmodern#101]
So simple-date has two "features" that might be worth looking at.

1. we only store milliseconds and months. Postgres stores microseconds (giving greater precision than simple-date), days, and months. The idea being that days can have 23 or 25 hours, in addition to 24. Should we support storing days and months too?

2. We encode an interval like -8 hours as -1 day +16 hours. Seems a bit odd. Keep as is or fix? It's particularly odd given that postgres' built in time zone stuff likes to express offsets to UTC as -N hours, so we end up with 1 day, 24-N hours.

**Comment by marijnh** [comment]
I don't want to touch simple-date anymore. It's superseded by local-time, and only kept around for backwards-compatibility. Also, it's very subtle code and making serious changes to it is almost certain to cause new bugs and compatibility issues.

**Comment by slyrus** [comment]
Ok, sounds good. Is there a local-time sql-reader? That sounds like it would be nice.

**Comment by marijnh** [comment]
Last time I checked they had it bundled with the library. Not sure if that's still the case.
