### ISSUE TITLE
Impossible to use PGPASSFILE

### ISSUE THREAD

**Issue by svetlyak40wt** [marijnh/Postmodern#103]
Hi! I have to use [special file to store PG credentials](https://www.postgresql.org/docs/9.2/static/libpq-pgpass.html). Psql utility and libpg supports it. For example, if PGPASSFILE environment variable points to a file with credentials, then I can omit password and psql will connect to the server.

But if I specify `nil` as a value for `password`, then I receive this `simple-error`: "Server requested md5-password authentication, but no password was given."

Is it possible to use credentials from PGPASS file?

**Comment by marijnh** [comment]
No, this is out of scope for this library. But you could create a wrapper/helper that handles it.

**Comment by svetlyak40wt** [comment]
Created a helper: https://github.com/svetlyak40wt/cl-pgpass
