### ISSUE TITLE
Documentation is vague about time intervals

### ISSUE THREAD

**Issue by svetlyak40wt** [marijnh/Postmodern#104]
I've read documentation and greped through sources but still don't understand how to use time intervals with s-sql.

For example, how to transform this query into the S-SQL:
```sql
SELECT id
  FROM migrations
 WHERE status = 'completed'
   AND updated_at > NOW() - INTERVAL '3 DAYS'
 ORDER BY updated_at DESC"
```

**Comment by sabracrolleton** [comment]
Hmm. Not immediately obvious to me. In the worst case, you could always do:

    (query (:select 'id :from 'migrations 
                    :where (:and (:= 'status "completed") 
                                 (:> 'updated-at 
                                     (:- (:now) (:raw "interval '600 days'"))))))

**Comment by sabracrolleton** [comment]
```
(query (:order-by
        (:select 'id
                 :from 'migrations
                 :where (:and
                         (:= 'status "completed")
                         (:> 'updated-at (:- (:now) (:interval ("3 days"))))))
        (:desc 'updated-at)))
```

**Comment by sabracrolleton** [comment]
See documentation interval-notes.html in doc directory.
