### ISSUE TITLE
Has something changed on timestamps?

### ISSUE THREAD

**Issue by sabracrolleton** [marijnh/Postmodern#105]
Has something changed with respect to timestamps?

    >psql -d testdb

    testdb=# select created_at from test_table where id = 1117;

     2016-12-01 21:08:41.422603-08

But I go into a repl and use postmodern and:

    (query "select create_at from test_table where id=1117" :single)
    3689641108

Where is the bigint coming from and what happened to my timestamp with timezones?

**Comment by slyrus** [comment]
Yes. The default readtable now returns an integer:

```
(in-package :cl-postgres-tests)

(with-test-connection
  (with-default-readtable
    (exec-query connection "select now()::timestamp with time zone;" 'list-row-reader)))
```

gives:
```
 ((3689647844))
```

The "default" behavior is that you get

**Comment by sabracrolleton** [comment]
Postgresql does not expect an integer when I am updating a dao. How do I
fix this?

Sabra

CREATE TABLE time_test (
    id integer NOT NULL,
    created_at timestamp with time zone
);

COPY time_test (id, created_at) FROM stdin;
1 2016-12-02 05:26:57.459133-08
2 2016-12-02 05:27:08.906286-08
3 2016-12-02 05:27:13.427379-08

(defclass time-test ()
  ((id :accessor id :col-type integer :initarg :id
               :initform 0)
   (created-at :accessor created-at :col-type timestamp :initarg
:created-at
               :initform (local-time:now)))
  (:metaclass postmodern:dao-class)
  (:table-name time-test)(:keys id))

(update-dao (get-dao 'time-test 1))

Database error 42804: column "created_at" is of type timestamp with time
zone but expression is of type bigint
HINT: You will need to rewrite or cast the expression.
QUERY: UPDATE time_test SET created_at = 3689674017 WHERE (id = 1)
   [Condition of type CL-POSTGRES-ERROR:SYNTAX-ERROR-OR-ACCESS-VIOLATION]

(cl-postgres:set-sql-datetime-readers :timestamp-with-timezone
 'local-time:universal-to-timestamp)

(update-dao (get-dao 'time-test 1))

The value
  16923699
is not of type
  (INTEGER -1000000 1000000)
   [Condition of type TYPE-ERROR]

**Comment by slyrus** [comment]
Well, I get a different answer from you, which is that the local-time:now value can't be converted to an SQL literal. That seems reasonable. If I change the :initform of created-at to something that postmodern knows about like:

```
(defclass time-test ()
  ((id :accessor id :col-type integer :initarg :id :initform 0)
   (created-at :accessor created-at :col-type timestamp :initarg :created-at
               :initform (simple-date:universal-time-to-timestamp
                          (local-time:timestamp-to-universal
                           (local-time:now)))))
  (:metaclass postmodern:dao-class)
  (:table-name time-test)
  (:keys id))
```

Then the following works:
```
(with-test-connection
  (execute (dao-table-definition 'time-test)))

(with-test-connection
  (let ((dao (make-instance 'time-test :id 1)))
    (insert-dao dao)))

(with-test-connection
  (let ((dao (make-instance 'time-test
                            :id 2
                            :created-at "2016-12-02 05:26:57.459133")))
    (insert-dao dao)))

(with-test-connection
  (let ((dao (get-dao 'time-test 1)))
    (update-dao dao)))
```

**Comment by slyrus** [comment]
You're not using https://github.com/radisb/postmodern-localtime/blob/master/postmodern-localtime.lisp are you?

That sounds interesting, but I haven't tested it.

**Comment by sabracrolleton** [comment]
Hello Cyrus,

Thank you for your help. I think I understand now and I had not focused on
simple-date. No, I have not tried postmodern-localtime.

On a separate note, I want to thank you for all the updates to Postmodern.
I have not really paid attention since I submitted the windows function
patch, but you have done a lot of work and I appreciate it. I suppose I
should go back through my examples article and update it.

Best wishes,

Sabra

**Comment by slyrus** [comment]
You're welcome! Thanks for the kind words. Glad to hear that your issue has been cleared up.

BTW, I wasn't really suggesting that you use postmodern-localtime, although that might be interesting. I just wanted to make sure that there wasn't some reason I was missing why the local-time:now value might have been expected to work. I should check postmodern-localtime too, but time is kind of a rat hole. I don't need all the bells and whistles :)

**Comment by sabracrolleton** [comment]
I am going to update my time/date section on
https://sites.google.com/site/sabraonthehill/postmodern-examples.

Do you mind if I quote you from your email on how to resolve my dao issue?

Sabra

**Comment by slyrus** [comment]
By all means. That looks like a very useful resource!
