### ISSUE TITLE
DEFPREPARED from two separate files compiled in two separate Lisp processes share statement IDs

### ISSUE THREAD

**Issue by abridgewater** [marijnh/Postmodern#109]
Create two files, each with a DEFPREPARED taking some number of parameters, different in each case. Start your lisp implementation, load Postmodern, COMPILE-FILE one of the files, and exit. Start the implementation again, load Postmodern, COMPILE-FILE the other file, and exit. Now, start the implementation a third time, load Postmodern, and both compiled files. Open a database connection and run both prepared statements with valid arguments. The second one _will_ fail: They both have the same statement IDs, thus the second one executed for a given connection thinks that it has already been prepared and will execute the SQL from the first, yielding a mismatch in the number of arguments required vs. supplied. And this is the _obvious_ manifestation. If the parameter sets are close enough, you could end up with code that silently does the wrong thing.

Easily enough fixed: use LOAD-TIME-VALUE around the allocation of STATEMENT-ID in the expansion produced by GENERATE-PREPARED.

**Comment by abridgewater** [comment]
In the cold light of morning, I'm no longer convinced that this is the case. I'll try to determine one way or another before Monday.

**Comment by sabracrolleton** [comment]
Did you ever determine if this was a postmodern problem?

**Comment by sabracrolleton** [comment]
Closed as no response was provided.
