### ISSUE TITLE
PREPARE INTERNs new KEYWORDs, but the documentation doesn't mention it

### ISSUE THREAD

**Issue by abridgewater** [marijnh/Postmodern#110]
This has been causing heap exhaustion in production for me for a while now, and I've only just tracked it down: Any time PREPARE is used, it invokes NEXT-STATEMENT-ID at runtime, and this interns a new KEYWORD. The documentation does not mention this at all, which meant that it came as a great surprise when a backtrace from an allocation failure had INTERN being called from a function using PREPARE.

On the one hand, okay, I probably earned a failure here _somehow_. On the other, some warning would have been nice.

**Comment by marijnh** [comment]
It looks like these don't need to be interned at all. If you want to submit a pull request removing the keywords, I'll take a look.

**Comment by sabracrolleton** [comment]
This should be fixed by todays last commit.
