### ISSUE TITLE
S-SQL Enhancement: dropdb / createdb

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#112]
This looks easy enough by adding them to:

(defmacro def-drop-op (op-name word)
  `(def-sql-op ,op-name (&rest args)
     (let ((if-exists (if (eq (car args) :if-exists) (pop args) nil)))
       (destructuring-bind (name) args
         `("DROP " ,,word " " ,@(when if-exists '("IF EXISTS ")) ,@(sql-expand name))))))

(def-drop-op :drop-table "TABLE")
(def-drop-op :drop-index "INDEX")
(def-drop-op :drop-sequence "SEQUENCE")
(def-drop-op :drop-view "VIEW")
(def-drop-op :drop-type "TYPE")
(def-drop-op :drop-rule "RULE")

Any reason that we do not have dropdb & createdb at the moment?

**Comment by Symbolics** [comment]
I've been using these, in case someone else has the same requirement:

```
(defun create-database (database)
  "Creating a database.
   If the database exists an error is raised."
  (execute (format nil "CREATE DATABASE ~a" (s-sql:to-sql-name database t))))

(s-sql::def-drop-op :drop-database "DATABASE")
```

**Comment by Symbolics** [comment]
Feature added in [pull request #116](https://github.com/marijnh/Postmodern/pull/116)

**Comment by sabracrolleton** [comment]
Added with modifications
