### ISSUE TITLE
bug in QUERY

### ISSUE THREAD

**Issue by asciinen** [marijnh/Postmodern#117]
There is a bug in the "query" macro: if any of the args is a form that evaluates "query", the result will be incorrect. The reason is that the macro first calls "prepare-query" and then evaluates the arguments.
Another call to the query macro will destroy the prepared query, since "query" always uses the same name for the prepared statement (empty string).

Here is a fix:

(defmacro query (query &rest args/format)
  "Execute a query, optionally with arguments to put in the place of
$X elements. If one of the arguments is a known result style or a class name,
it specifies the format in which the results should be returned."
  (let* ((format :rows)
         (args (loop :for arg :in args/format
		     :if (or (dao-spec-for-format arg)
			     (assoc arg *result-styles*)) :do (setf format arg)
                     :else :collect arg)))
    (destructuring-bind (reader result-form) (reader-for-format format)
      (let ((base (if args
		      (let ((vars (loop for x in args collect (gensym))))
			`(let ,(loop for v in vars for a in args collect `(,v ,a))
			   (prepare-query *database* "" ,(real-query query))
			   (exec-prepared *database* "" (list ,@vars) ,reader)))
		      `(exec-query *database* ,(real-query query) ,reader))))
        `(,result-form ,base)))))

**Comment by marijnh** [comment]
This was fixed via #118
