### ISSUE TITLE
schema-exist-p misnamed?

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#125]
I have wondered for a while now if this is a typo. The other functions for [inspecting the database](http://marijnhaverbeke.nl/postmodern/postmodern.html#inspect) all use the exists convention (note the 's' at the end).

Should this be schema-exists-p ?

**Comment by sabracrolleton** [comment]
schema-exists-p now added. schema-exist-p is documented as deprecated but still available to avoid breakage..
