### ISSUE TITLE
Contrib directory?

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#126]
I have a collection of utilities, mostly taken from the @sabracrolleton [Postmodern examples website](https://sites.google.com/site/sabraonthehill/postmodern-examples) that I use in Postmodern project with Greenplum. Initially I was going to put this out as a separate project on github as 'pomo-utilities', but wonder what the group here thinks about a contrib/ directory in this repository?

A contrib directory has the advantage of examples right inside the repository and, potentially, the postmodern examples website merged into the documentation. Essentially I think I am saying that a merger of these two projects is better than 3 separate places for information (utilities repo, code repo and website examples).

**Comment by marijnh** [comment]
(I no longer maintain this, so I'm only offering my advice but: contrib directories are a nightmare for maintainers. You'll either have to deeply review and fix all the contributed code, or forever deal with bug reports about possibly terrible code that you didn't write. Contrib dirs are mostly a kludge to deal with the fact that there didn't use to be good package managers. We don't need them anymore, now that distributing separate packages is easy.)

**Comment by sabracrolleton** [comment]
I generally agree with Marijn on contrib directories. However, seeing as how they are "mostly taken" from my examples website, and I am now maintaining Postmodern, I suppose I should pay some attention to them. Some of them should be included in the mainline anyway.  One issue with some of those utilities is they may or may not work with different versions of postgresql as sometimes upstream changed the catalog schema.

Symbolics, please pm me with details of what you are using.

**Comment by sabracrolleton** [comment]
Decision made not to have contrib directories.  I can work with people who want to add utilities to the mainline.
