### ISSUE TITLE
*-dao operations are not thread safe if dao-class is not finalized

### ISSUE THREAD

**Issue by tshatrov** [marijnh/Postmodern#134]
Suppose I start a fresh Lisp instance, and load a file with a few Postmodern table definitions. I then run a suite of tests which uses get-dao method to retrieve data from database. I previously ran the tests sequentially but recently I started to run them in several threads to save time. Immediately I started getting strange errors like this

```
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "lparallel" RUNNING {1007AF1723}>:
  Class ENTRY has no key slots.
WARNING:
   redefining POSTMODERN:DAO-EXISTS-P (#<POSTMODERN:DAO-CLASS ICHIRAN/DICT::ENTRY>) in DEFMETHOD
WARNING:
   redefining POSTMODERN:UPDATE-DAO (#<POSTMODERN:DAO-CLASS ICHIRAN/DICT::ENTRY>) in DEFMETHOD
WARNING:
   redefining POSTMODERN:UPSERT-DAO (#<POSTMODERN:DAO-CLASS ICHIRAN/DICT::ENTRY>) in DEFMETHOD
WARNING:
   redefining POSTMODERN:DELETE-DAO (#<POSTMODERN:DAO-CLASS ICHIRAN/DICT::ENTRY>) in DEFMETHOD
WARNING:
   redefining POSTMODERN:GET-DAO (#<SB-MOP:EQL-SPECIALIZER ICHIRAN/DICT::ENTRY>) in DEFMETHOD
WARNING:
   redefining POSTMODERN:INSERT-DAO (#<POSTMODERN:DAO-CLASS ICHIRAN/DICT::ENTRY>) in DEFMETHOD
WARNING:
   redefining POSTMODERN::FETCH-DEFAULTS (#<POSTMODERN:DAO-CLASS ICHIRAN/DICT::ENTRY>) in DEFMETHOD
WARNING:
   redefining SHARED-INITIALIZE :AFTER (#<POSTMODERN:DAO-CLASS ICHIRAN/DICT::ENTRY>
                                        #<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
```

After delving into [postmodern codebase](https://github.com/marijnh/Postmodern/blob/master/postmodern/table.lisp#L137), I believe there is a problem with table classes being finalized not when the code is loaded, but when they are first accessed by a *-dao method. So in a multi-thread scenario one table might be finalized in several threads at once, or `class-finalized-p` might return `t` before `finalize-inheritance :after` is run in another thread.

The workaround would be manually going through `postmodern::*tables*` and finalizing every table before any multi-threaded code is run.

**Comment by sabracrolleton** [comment]
Since you have already started looking at the code, do you have a proposed fix?

**Comment by sabracrolleton** [comment]
Looking at my typical code, I have a call to 

`(closer-mop:ensure-finalized (find-class insert-name-of-class))`

right after every class definition.

**Comment by tshatrov** [comment]
Well, wrapping a bordeaux-threads lock around 

```
    (unless (class-finalized-p class)
       (finalize-inheritance class))
```
(if feature `:postmodern-thread-safe` is present) is one possible solution.

**Comment by sabracrolleton** [comment]
Thank you. Will look at it and test.

**Comment by sabracrolleton** [comment]
Resolved in commit of 26 Apr 2018
