### ISSUE TITLE
Question: what are the plans?

### ISSUE THREAD

**Issue by fstamour** [marijnh/Postmodern#142]
I'm seeing a lot of activity on this repo recently, I saw that @sabracrolleton is now the maintainer.

I was just curious to know if there was any peculiar plan for this (awesome) project?

**Comment by sabracrolleton** [comment]
I am trying to add some of the features that have been included in postgresql in the last few years and start cleaning up issues that have been left dormant. That also requires adding a lot more testts. It will probably be a couple of weeks until I have a full roadmap together.

**Comment by fstamour** [comment]
Cool, nice work!

**Comment by sabracrolleton** [comment]
See draft roadmap in root directory. Changes in priority and people willing to help are welcomed.
