### ISSUE TITLE
Revisit NIL-NULL-"false" behavior

### ISSUE THREAD

**Issue by sabracrolleton** [marijnh/Postmodern#148]
Is possible to change the behaviour of postmodern, so that a NULL value in the table produced a NIL on the lisp side (instead of the :null symbol), and a NIL value would be written as a NULL, instead of false? The current behaviour, though it makes sense for columns with type “boolean”, is out-of-tune with lisp (NULL being true), and requires verbose and error-prone code in most cases. Furthermore, it leads to the following irregularity in case of columns with type "text":

if a (text-typed) slot's value is NIL, the string "false" will be written in the database. It will then be retrieved as the string "false", not NIL.

Thus, read(write(NIL)) != NIL

As a reference, see earlier discussion on the mailing list: https://mailman.common-lisp.net/pipermail/postmodern-devel/2013-July/000812.html

**Comment by preetpalS** [comment]
How would you make a distinction between the Boolean false value and NULL then?

**Comment by sabracrolleton** [comment]
That is exactly the problem.
