### ISSUE TITLE
Workaround needed when using library (via quicklisp) with ABCL 1.5.0 on Windows (x64)

### ISSUE THREAD

**Issue by preetpalS** [marijnh/Postmodern#149]
I had to load the *usocket* library manually (`(ql:quickload :usocket)`) in order to successfully use this library (via quicklisp) on ABCL on Windows (this is the only platform I tested). I also tested this library on Clozure CL and SBCL on Windows (it works on those implementations without issues).

The following is a minimal test case (minimal-test-case.lisp):

```elisp
(ql:quickload :postmodern)
(use-package :postmodern)
```

The following is how I executed the code on Windows using the command line:

```
x:\test>java -jar X:\lisp\abcl-bin-1.5.0\abcl.jar --load minimal-test-case.lisp
Armed Bear Common Lisp 1.5.0
Java 10.0.1 Oracle Corporation
Java HotSpot(TM) 64-Bit Server VM
Low-level initialization completed in 0.981 seconds.
Startup completed in 8.387 seconds.
Loading C:\Users\ps\.abclrc completed in 50.719 seconds.
To load "postmodern":
   Load 1 ASDF system:
    postmodern
; Loading "postmodern"
...
Error loading C:/Users/ps/AppData/Local/cache/common-lisp/abcl-1.5.0-fasl43-win-x64/C/Users/ps/quicklisp/dists/quicklisp/software/postmodern-20180430-git/cl-postgres/public.abcl at line 31 (offset 2618)
#<THREAD "interpreter" {7A60A8FF}>: Debugger invoked on condition of type ERROR
  USOCKET is not the name of a package.
Restarts:
  0: TRY-RECOMPILING               Recompile public and try loading it again
  1: RETRY                         Retry loading FASL for #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-postgres" "cl-postgres" "public">.
  2: ACCEPT                        Continue, treating loading FASL for #<ASDF/LISP-ACTION:CL-SOURCE-FILE "cl-postgres" "cl-postgres" "public"> as having been successful.
  3: RETRY                         Retry ASDF operation.
  4: CLEAR-CONFIGURATION-AND-RETRY Retry ASDF operation after resetting the configuration.
  5: ABORT                         Give up on "postmodern"
[1] CL-POSTGRES(1):
```

**Comment by preetpalS** [comment]
I am relatively new to using Common Lisp (I decided to use it after working with Emacs Lisp). I am mainly using it for exploring and transforming some data in a database application. I'd be happy to provide more relevant information if needed and perhaps test a fix on my local machine if necessary.

**Comment by sabracrolleton** [comment]
I do not have a windows machine available to test on.  If you edit line 15 of cl-postgres.asd to include :armedbear and start over cleanly, does it now work for you?

**Comment by preetpalS** [comment]
@sabracrolleton Your fix works, I submitted a pull request for the fix.
