### ISSUE TITLE
URL in repository description is broken

### ISSUE THREAD

**Issue by phoe** [marijnh/Postmodern#172]
http://marijn.haverbeke.nl/postmodern leads to:
![zrzut ekranu z 2018-10-19 21-07-15](https://user-images.githubusercontent.com/15045546/47238605-046ba300-d3e3-11e8-9c90-567061fd46a9.png)

**Comment by sabracrolleton** [comment]
url works for me. Can you check again?

**Comment by PuercoPop** [comment]
Just as a data point, works for me as well. Maybe it was something temporary?

**Comment by phoe** [comment]
Video demonstrating the issue: https://streamable.com/cyeqf

**Comment by sabracrolleton** [comment]
Great demonstration of the symptom. I can see the correct url shows up at the bottom left when you hover over the link. 

I am at a loss as to what is inserting the redirect.  Do you use codemirror in your browser? What happens if you type in the url directly?

**Comment by phoe** [comment]
```
┌─[phoe][phoetower][/tmp]
└─▪ LANG=C wget http://marijn.haverbeke.nl/postmodern
--2018-10-20 17:10:12--  http://marijn.haverbeke.nl/postmodern
Resolving marijn.haverbeke.nl (marijn.haverbeke.nl)... 2a01:7c8:aab0:26e:5054:ff:fe3a:8388, 149.210.142.219
Connecting to marijn.haverbeke.nl (marijn.haverbeke.nl)|2a01:7c8:aab0:26e:5054:ff:fe3a:8388|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://discuss.codemirror.net/postmodern [following]
--2018-10-20 17:10:12--  https://discuss.codemirror.net/postmodern
Resolving discuss.codemirror.net (discuss.codemirror.net)... 2a01:7c8:aab0:26e:5054:ff:fe3a:8388, 149.210.142.219
Connecting to discuss.codemirror.net (discuss.codemirror.net)|2a01:7c8:aab0:26e:5054:ff:fe3a:8388|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-10-20 17:10:12 ERROR 404: Not Found.
```

What does the wget log look like for you?

**Comment by sabracrolleton** [comment]
wget http://marijn.haverbeke.nl/postmodern
--2018-10-20 08:14:05--  http://marijn.haverbeke.nl/postmodern
Resolving marijn.haverbeke.nl (marijn.haverbeke.nl)... 149.210.142.219, 2a01:7c8:aab0:26e:5054:ff:fe3a:8388
Connecting to marijn.haverbeke.nl (marijn.haverbeke.nl)|149.210.142.219|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://marijnhaverbeke.nl/postmodern [following]
--2018-10-20 08:14:05--  http://marijnhaverbeke.nl/postmodern
Resolving marijnhaverbeke.nl (marijnhaverbeke.nl)... 149.210.142.219, 2a01:7c8:aab0:26e:5054:ff:fe3a:8388
Reusing existing connection to marijn.haverbeke.nl:80.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://marijnhaverbeke.nl/postmodern/ [following]
--2018-10-20 08:14:06--  http://marijnhaverbeke.nl/postmodern/
Reusing existing connection to marijn.haverbeke.nl:80.
HTTP request sent, awaiting response... 200 OK
Length: 22275 (22K) [text/html]
postmodern: Is a directory

Interesting. Different result after the 301 message.

**Comment by sabracrolleton** [comment]
302 and 301 and different result. Hmmm. Will ping marijn and see if it makes any sense from his side.

**Comment by marijnh** [comment]
Ahh, that explains why it wasn't showing up in grep or search. Fixed!

**Comment by phoe** [comment]
Thanks!
