### ISSUE TITLE
SIMPLE-DATE broken + current_timestamp broken

### ISSUE THREAD

**Issue by phoe** [marijnh/Postmodern#173]
I am using examples from https://sites.google.com/site/sabraonthehill/postmodern-examples/postmodern-time-functions don't work.

On postmodern from the current Quicklisp release:

```
CL-USER> (ql:quickload :postmodern)
To load "postmodern":
  Load 1 ASDF system:
    postmodern
; Loading "postmodern"
.
(:POSTMODERN)
CL-USER> (ql:quickload :simple-date)
To load "simple-date":
  Load 1 ASDF system:
    simple-date
; Loading "simple-date"

(:SIMPLE-DATE)
CL-USER> (setf postmodern:*database* (postmodern:connect "dbname" "user" "password" "localhost"))
#<CL-POSTGRES:DATABASE-CONNECTION {101088E0A3}>
CL-USER> (postmodern:query (:select (:now)))
((3748965312))
1
CL-USER> (postmodern:query (:select 'current-timestamp) :single)
;; Database error 42703: column "current_timestamp" does not exist
;; QUERY: (SELECT "current_timestamp")
```

1) Asking for `now()` after loading `SIMPLE-DATE` should not return integers.
2) Asking for `current_timestamp` should not signal an error.

**Comment by phoe** [comment]
Welp - I didn't study the documentation hard enough to find the simple-date example.

Thanks!

**Comment by FiV0** [comment]
@sabracrolleton When you say "per simple-date doc" you mean [this](http://marijnhaverbeke.nl/postmodern/simple-date.html#timestamp)? Because there is no mention of explicitly loading `simple-date/postgres-glue`. So when you follow the [quickstart example](http://marijnhaverbeke.nl/postmodern/#quickstart) with a timestamp:
```
(defclass repository()                                                          
    ((origin-url :col-type string                                                 
                 :initarg :origin                                                 
                 :accessor :repo-origin)              
     (time :col-type timestamp                                                    
           :initarg :time                                                         
           :accessor :repo-time))            
    (:metaclass dao-class)                                                        
    (:keys origin-url)) 

(execute (dao-table-definition 'repository))
(insert-dao (make-instance 'repository
                           :origin "test"                                                 
                           :time (universal-time-to-timestamp (get-universal-time))))
```
you will get an error. I looked for quite a while before I figured what was going on. Maybe make that more explicit in the simple-date doc.

**Comment by sabracrolleton** [comment]
Sorry for the delay. I was referring to the documentation which accompanies the source code and is in github. https://github.com/marijnh/Postmodern/blob/master/doc/index.org and https://github.com/marijnh/Postmodern/blob/master/doc/simple-date.org. The documentation at http://marijnhaverbeke.nl/postmodern/ are not always as up to date as the documentation in the package.

I will try to make it even more clear in the documentation.
