### ISSUE TITLE
:reconnect restart not good for prepared statements

### ISSUE THREAD

**Issue by MauDagos** [marijnh/Postmodern#178]
Hello,

We've recently introduced into our code the use of the :reconnect restart offered by errors of type database-connection-error. However, we've discovered that this restart is not good for when we're executing prepared statements. Whenever a prepared statement fails and we invoke :reconnect, we get errors like:

`Database error 26000: unnamed prepared statement does not exist` - when we're passing &rest parameters to pomo:execute.

`Database error 26000: prepared statement "STATEMENT-1" does not exist` - when we're using pomo:defprepared.

We believe it's a bug in the library's restart code. In these cases it should ensure that the prepared statement exists in the reopened database connection.

Best regards,

Mauro

**Comment by sabracrolleton** [comment]
Can you give me an example of how you are invoking :reconnect and calling the prepared statement?

**Comment by MauDagos** [comment]
`(pomo:defprepared example-stmt
    "UPDATE example_table
        SET value_1 = $1
      WHERE value_2 = $2 AND value_3 = $3;"
  :none)`

`(let ((db-spec (list "db" "user" "pass" "localhost" :port 5432 :pooled-p t)))
  (handler-bind
      ((postmodern:database-connection-error
        (lambda ()
          (sleep 1)
          (invoke-restart :reconnect))))
    (postmodern:with-connection db-spec
      (postmodern:execute
       "UPDATE example_table
           SET value_1 = $1
         WHERE value_2 = $2 AND value_3 = $3;"
       "1" "2" "3"))
    (postmodern:with-connection db-spec
      (example-stmt "1" "2" "3"))))`

Here's a quick example I've written for both error cases posted above.

**Comment by sabracrolleton** [comment]
I am having difficulty recreating the errors. If I try the following example:

```
(defprepared sny1 (:select 'name :from 'employee :where (:= 'city "New York")) :rows)

(defun test7 ()
  (let ((db-spec (list "test" user password "localhost")))
    (with-connection db-spec
      (handler-bind ((database-connection-error
                      (lambda (condition) (format t "Error message ~a and close~%" condition)
                        (invoke-restart :reconnect))))                          
        (format t "First Query before termination ~%~a ~%PID ~a~%"
                (query (:select 'name :from 'employee :where (:= 'city "New York")))
                (query (:select (:pg-backend-pid)) :single))
        (sleep 10)
        (format t "New PID ~a~%" (query (:select (:pg-backend-pid)) :single))
        (funcall 'sny1)))))
```
and then terminate the backend from another session during the sleep period, I get a result like this:

First Query before termination 
((Linda) (Alison) (Jason3)) 
PID 2335
Error message Database error 57P01: terminating connection due to administrator command
QUERY: (SELECT pg_backend_pid()) and close
New PID 2345
(("Linda") ("Alison") ("Jason3"))

This example successfully reconnected with a new PID and the defprepared statement sny1 is successfully called in the new session.

I am obviously missing something. Can you flag what I need to change to replicate the problem?

**Comment by sabracrolleton** [comment]
I was focusing on the funcall to the defprepared syn1, not the PID query, but that seems not relevant based on the additional information. Thank you for the additional information - it focuses the problem more clearly for me.

**Comment by sabracrolleton** [comment]
Not forgotten. I have a solution in testing.

**Comment by MauDagos** [comment]
Much appreciated. :slightly_smiling_face:

**Comment by sabracrolleton** [comment]
Please look at the pull request I have submitted, but not yet merged. I would like to see if you have any concerns or changes before I merge it.

**Comment by MauDagos** [comment]
Thanks @sabracrolleton. I haven't had time to inspect or test your changes, I will do so and get back to you asap.

**Comment by sabracrolleton** [comment]
Not yet resolved.

**Comment by sabracrolleton** [comment]
MauDagos, please look at the latest commits and see if that resolves the problem.

**Comment by MauDagos** [comment]
Sorry for lack of response from my side, I got deviated from the project running this library. I will give feedback sometime this week.

**Comment by MauDagos** [comment]
Going over the git-blame of the file cl-postgres/public.lisp, I found this commit https://github.com/marijnh/Postmodern/commit/3572c4a4566558ddb4fc6f85540ab65c27055e32. I was intrigued because this commit does not exist in the version of the Postmodern library being used in the project. That is, we are using an older version.

Still, going over the code, I think it might be ok now. I'm not at the office right now and don't have the necessary tools for actually trying the code out, I'll try it out whenever I can. Thanks!

**Comment by sabracrolleton** [comment]
Ok. We will tentatively close this issue.
