### ISSUE TITLE
Polish characters in warnings are omitted

### ISSUE THREAD

**Issue by phoe** [marijnh/Postmodern#191]
While dropping a type that doesn't exist:

CL REPL:
```
GATEWAY/SQL> (with-db () (pomo:query "DROP TYPE IF EXISTS chapter_permission_type;"))
WARNING:
   PostgreSQL warning: typ "chapter_permission_type" nie istnieje, pominito
```

psql:
```
gateway=> DROP TYPE IF EXISTS chapter_permission_type;
UWAGA:  typ "chapter_permission_type" nie istnieje, pominięto
```

There is a difference in the last word, `pominito` vs `pominięto` - a Polish character `ę` is silently dropped from the warning.
My PostgreSQL is set to Polish locale.
postmodern is the current Quicklisp version.

**Comment by phoe** [comment]
This issue is further annoying, as strings having multiple Polish characters are barely readable:

```
bd skadni na kocu danych wejciowych
błąd składni na końcu danych wejściowych
```

**Comment by sabracrolleton** [comment]
Interesting. Which lisp are you using?

**Comment by phoe** [comment]
SBCL 1.5.0 on Linux.

**Comment by sabracrolleton** [comment]
Ok. Have validated the problem on both sbcl and ccl.

**Comment by phoe** [comment]
```lisp
SQL/TEST> (pomo:query "DROP TYPE IF EXISTS chapter_permission_types;")
WARNING:
   PostgreSQL warning: typ "chapter_permission_types" nie istnieje, pominięto
NIL
```

Now that's better! 936a76c1 fixed it. Thanks!
