### ISSUE TITLE
A way of executing .sql files

### ISSUE THREAD

**Issue by phoe** [marijnh/Postmodern#192]
After browsing Postmodern and CL-Postgres manuals and code, I have not seen the option to execute the contents of a `.sql` file from Lisp, something that is analogous to `psql < file.sql` in Unix shell.

Is there such a way that doesn't involve preparing all the individual statements inside a given file (which might not be fully possible in case of transactions)?

**Comment by phoe** [comment]
#lisp gave me an answer:
```
16:30 < phoe> How can I execute a .sql file using postmodern?
16:30 < phoe> A naïve way causes an error to be signaled: "cannot insert
              multiple commands into a prepared statement"
16:31 < phoe> the .sql file contains multiple statements.
17:29 < dim> you need to parse the file down to single statements
17:30 < dim> you can use my code for that from pgloader at
https://github.com/dimitri/pgloader/blob/master/src/utils/read-sql-files.lisp
17:30 < dim> phoe: the reason why it fails is that Postmodern is using the
             PostgreSQL extended query protocol which works with a query at a
             time, with out-of-line parameters (good to avoid SQL injections)
17:31 < dim> the trade-off is that you then need to make sure in the app that
             you're sending one query at a time using that protocol
17:32 < dim> https://github.com/dimitri/pgloader/blob/master/src/utils/read-sql-files.lisp 
             implements a simple hand-written parser for SQL queries delited
             with a semi-colon (;)... not that simple, it knows about
             dollar-quoting and other forms of escaping
17:32 < dim> select E'\';' as ";"; is an example of a corner-case when parsing
             SQL queries from a file
17:33 < dim> the result is a single value '; in a column named ;
```

Therefore, if I understand correctly, it is impossible for postmodern to grab a whole file and pass it to Postgres without parsing.

Would it therefore be beneficial to include a function like `(postmodern:execute-file #p"/home/phoe/foo.sql")` in Postmodern that utilizes code from https://github.com/dimitri/pgloader/blob/master/src/utils/read-sql-files.lisp to parse a SQL file into individual queries and then executes them in order? Should that code be in the postmodern repository, or should a separate QL system be created for it?

**Comment by phoe** [comment]
https://github.com/phoe/postmodern-execute-file happened, and is good enough for my use case. If you feel that it would be good to merge this utility with mainline, please tell me, and I'll prepare a PR; if not, please just close this issue.

**Comment by sabracrolleton** [comment]
That looks like a useful utility. Please submit a pull request.

**Comment by phoe** [comment]
OK.

How should I deal with licensing in the pull request? I will be copying a code snippet from pgloader that is licensed under the [PostgreSQL License](https://github.com/phoe/postmodern-execute-file/blob/master/LICENSE).

```
pgloader

Copyright (c) 2005-2017, The PostgreSQL Global Development Group

Permission to use, copy, modify, and distribute this software and its documentation for any purpose, without fee, and without a written agreement is hereby granted, provided that the above copyright notice and this paragraph and the following two paragraphs appear in all copies.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
```

**Comment by Symbolics** [comment]
That looks like the BSD 3-clause license...

    On Friday, March 22, 2019, 9:15:47 PM GMT+8, Michał Herda <notifications@github.com> wrote:  
 
 
OK.

How should I deal with licensing in the pull request? I will be copying a code snippet from pgloader that is licensed under the PostgreSQL License.
pgloader

Copyright (c) 2005-2017, The PostgreSQL Global Development Group

Permission to use, copy, modify, and distribute this software and its documentation for any purpose, without fee, and without a written agreement is hereby granted, provided that the above copyright notice and this paragraph and the following two paragraphs appear in all copies.

IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

**Comment by sabracrolleton** [comment]
Can you get an email from Dimitri allowing the usage?

**Comment by phoe** [comment]
@Symbolics Yes, it is. As far as I understand, this now means that Postmodern will need to update its LICENSE file to show that it contains this BSD-3 licensed code.

@sabracrolleton If I understand correctly, we are able to use it now, as long as we display pgloader license next to Postmodern's in the license file.

**Comment by phoe** [comment]
PR available at https://github.com/marijnh/Postmodern/pull/193

**Comment by sabracrolleton** [comment]
Phoe's pull request committed.
