### ISSUE TITLE
Should trivial-utf-8 be an ASDF dependency?

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#203]
Currently cl-postgres/trivial-utf-8.lisp is a copy of the code at http://common-lisp.net/project/trivial-utf-8/ at some point in time.

Does it make sense to maintain this independently, or to add it as a dependency in the asd file?

**Comment by Symbolics** [comment]
I guess I could have been a bit more clear. Perhaps adding it as a ASDF subsystem is what I meant, e.g. in cl-postgres.asd, `(defsystem cl-postgres/trivial-utf8 ...`

**Comment by sabracrolleton** [comment]
trivial-utf-8 has not been updated since 2011 and I do not expect any updates in the future. The more interesting question would be whether there are reasons to use a different utf8 library.

**Comment by Symbolics** [comment]
Well, my first thought is 'no', unless something is gained from a different utf8 library. There is some clarity gained by making it a separate ASDF system. I'm happy to do this as part of my Genera updates (in a separate commit of course).

**Comment by sabracrolleton** [comment]
Closed as Symbolics included this in a Genera update.
