### ISSUE TITLE
cl-postgres/public.lisp from HEAD has undefined functions

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#204]
It appears something is wrong with cl-postgres/public.lisp. To reproduce:

1. Move your current Postmodern directory out of the ASDF tree to a temporary location
2. Clone / checkout the latest version from this repository
3. Compile either cl-postgres or postmodern systems (asdf:compile-system "cl-postgres")

Output:
````
; compilation unit finished
;   Undefined functions:
;     CL-POSTGRES::UNIX-SOCKET-CONNECT CL-POSTGRES::UNIX-SOCKET-PATH
;   Undefined variable:
;     CL-POSTGRES::*UNIX-SOCKET-DIR*
;   caught 1 WARNING condition
;   caught 3 STYLE-WARNING conditions
;   printed 123 notes
```
This is with SBCL. Also happens with CCL.

**Comment by Symbolics** [comment]
Not sure if it's relevant, but this is on MS Windows 10.

**Comment by Symbolics** [comment]
```
CL-USER> *features*
(CL-POSTGRES.FEATURES:SBCL-IPV6-AVAILABLE CL-POSTGRES.FEATURES:SBCL-AVAILABLE
 :SPLIT-SEQUENCE :SWANK :QUICKLISP :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2
 :ASDF :OS-WINDOWS :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :X86-64 :64-BIT
 :64-BIT-REGISTERS :ALIEN-CALLBACKS :ANSI-CL :AVX2 :C-STACK-IS-CONTROL-STACK
 :CALL-SYMBOL :COMMON-LISP :COMPARE-AND-SWAP-VOPS :CYCLE-COUNTER
 :FP-AND-PC-STANDARD-SAVE :GENCGC :IEEE-FLOATING-POINT :INTEGER-EQL-VOP
 :LINKAGE-TABLE :LITTLE-ENDIAN :OS-PROVIDES-DLOPEN :OS-PROVIDES-PUTWC
 :PACKAGE-LOCAL-NICKNAMES :SB-DOC :SB-DYNAMIC-CORE :SB-EVAL :SB-FUTEX :SB-LDB
 :SB-PACKAGE-LOCKS :SB-QSHOW :SB-SAFEPOINT :SB-SAFEPOINT-STRICTLY :SB-SIMD-PACK
 :SB-SIMD-PACK-256 :SB-SOURCE-LOCATIONS :SB-THREAD :SB-THRUPTION :SB-UNICODE
 :SB-WTIMER :SBCL :STACK-ALLOCATABLE-CLOSURES :STACK-ALLOCATABLE-FIXED-OBJECTS
 :STACK-ALLOCATABLE-LISTS :STACK-ALLOCATABLE-VECTORS
 :STACK-GROWS-DOWNWARD-NOT-UPWARD :UNDEFINED-FUN-RESTARTS
 :UNWIND-TO-FRAME-AND-CALL-VOP :WIN32)
```

**Comment by sabracrolleton** [comment]
Hmm. looks like an issue when running on windows. Unfortunately I do not have any windows boxes. Does anyone have any recommendations on dealing with unix-sockets while running on windows?

**Comment by Symbolics** [comment]
I’ll look into it further tomorrow. Can you think of anything with sockets that changed in the last year? It was working fine Q3 2018 (I think, I may have switched to Genera by then)

**Comment by Symbolics** [comment]
I'm going to close this with 'cannot reproduce'. This must have been some odd state things were in, but it's not reproducible now. With the exception of 3 tests in postmodern-execute-file all the tests for Postmodern on Windows pass on CCL and SBCL.
