### ISSUE TITLE
Documentation Contributions

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#205]
Looking to submit some contributions to documentation, and notice that the HTML appears to now be generated from the .org files. Is this the case? If so, does this happen automatically, or does it need to be done prior to a commit? (i.e. commit both the updated .org file and the .html, or just the .org)

Whilst we're here, is anyone working on the UUID stuff? I've got a need for that soon.

**Comment by sabracrolleton** [comment]
At the moment it needs to be done prior to a commit (or if someone just makes a change to the org files then I will  update the html files or vice versa). We do not have a lot of volume so it has not been as issue up to now.

**Comment by Symbolics** [comment]
How is the documentation generated from the org files? Is there a particular toolchain for this?

**Comment by sabracrolleton** [comment]
If you are using emacs, then it is just a question of C-c C-e H h. If you are not using emacs, then there are probably other toolchains such as pandoc that will do it. One item that I find irritating about automatically generating html from orgmode files is that emacs will automatically regenerate new ids in the html, which means that every line is different and needs to be committed if you are blindly using git.

**Comment by Symbolics** [comment]
It may be worth having a "How to Contribute" document to capture the questions & answers around this topic.

**Comment by phoe** [comment]
> At the moment it needs to be done prior to a commit (or if someone just makes a change to the org files then I will update the html files or vice versa)

I suggest adding Travis CI configuration that automatically generates documentation from Org to HTML on each commit and deploys it on GitHub Pages.

**Comment by sabracrolleton** [comment]
Going the leave the process the way it is.
