### ISSUE TITLE
Proposal: Add :if-exists keyword for drop-schema function

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#206]
Currently I've been dropping schemas by wrapping them in a (when schema-exists-p ... conditional. This would be cleaner drop-schema had an :if-exists keyword instead.

FYI, :drop-database accepts the :if-exists keyword, via the def-drop-op macro. It might be good to add this to the documentation of :drop-database at the same time.

**Comment by sabracrolleton** [comment]
Will accept a patch.

**Comment by sabracrolleton** [comment]
Updated docs in today's commit.
