### ISSUE TITLE
Conditionalizing on Versions

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#208]
Does anyone have a good way to conditionalize on a Postgres version? For example if implementing the list-data-base roles function, there are role attributes that only exist in a certain version of Postgres, e.g.:
```lisp
(:as 'r.rolreplication 'replicationp) ;postgresql 9.3+
(:as 'r.rolbypassrls 'bypass-row-level-security-p) ;postgresql 9.5+
```
It would be nice if, somewhere early on in loading pomo, we could push values onto `*features*`, such as pg for Postgres or gp for Greenplum, as well as a version and then use them in writing conditional statements. I read the Dynamic Query Notes, but it is not clear how this might work in this case. This was discussed before in issue #127, and part of the problem is that these are macros. Still, it seems like the macro expansion could contain the conditionals (?). I'm not a macro expert and would welcome any suggestions on around how to accomplish this.

**Comment by sabracrolleton** [comment]
It will go on my to do list, but right now I cannot promise being able to look at it before January.

**Comment by sabracrolleton** [comment]
Just added an easy cl-postgres function that returns the version of the connected postgresql instance as a float. This does not yet fully address your request, but is a start.

**Comment by svantevonerichsen6906** [comment]
A version as a float seems wrong to me.  How do you convert the versions `9.13.3` and `9.1.33`?  Why not leave it a string, or, if you feel that a parsing step is necessary, a list of integers?

**Comment by sabracrolleton** [comment]
You are right. Pre postgresql version 10, there were three part versions. Will leave it as a string.

**Comment by sabracrolleton** [comment]
Symbolics,

We now have the function (postgresql-version-at-least (desired-version-string connection)) in cl-postgres/public.lisp

Takes a postgresql version number which should be a string with the major and
minor versions separated by a period e.g. '12.2' or '9.6.17'. Checks against the
connection understanding of the running postgresql version and returns t if the
running version is the requested version or newer.

Does this give you the functionality you were looking for?

**Comment by Symbolics** [comment]
Perfect, thanks.

    On Monday, June 22, 2020, 12:51:11 AM GMT+8, Sabra Crolleton <notifications@github.com> wrote:  
 
 


Symbolics,

We now have the function (postgresql-version-at-least (desired-version-string connection)) in cl-postgres/public.lisp

Takes a postgresql version number which should be a string with the major and
minor versions separated by a period e.g. '12.2' or '9.6.17'. Checks against the
connection understanding of the running postgresql version and returns t if the
running version is the requested version or newer.

Does this give you the functionality you were looking for?
