### ISSUE TITLE
create-extended-table vs. create-table-full

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#209]
It looks like these two macros do very similar things. Is there a use case that is appropriate for one but not the other? Should these be consolidated?

**Comment by sabracrolleton** [comment]
Originally one was intended to work with additional functionality provided in postgresql v. 10 and 11, but I have not had the time to work out the versioning needed to make it efficient.  It is on my to do list.

**Comment by sabracrolleton** [comment]
Create-table-full now removed.
