### ISSUE TITLE
Test systems do not build for me

### ISSUE THREAD

**Issue by quicklisp** [marijnh/Postmodern#212]
http://report.quicklisp.org/2019-09-24/failure-report/postmodern.html has the full log.

The failures are of the form `The name "SIMPLE-DATE" does not designate any package.` and `The name "CL-POSTGRES-TESTS" does not designate any package.`,

**Comment by quicklisp** [comment]
This remains a problem for me - log is here: http://report.quicklisp.org/2019-10-14/failure-report/postmodern.html

**Comment by sabracrolleton** [comment]
Is it still a problem?

**Comment by quicklisp** [comment]
Looks great now, thank you!
