### ISSUE TITLE
postgresql-12 wants to use SHA256 instead of MD5 for password encryption

### ISSUE THREAD

**Issue by sabracrolleton** [marijnh/Postmodern#217]
We need to update the authentication protocols.

**Comment by phoe** [comment]
Ironclad has SHA256 support. We'll likely need to start depending on it.

Is there any kind of negotiation for the password encryption scheme? I don't think we can safely drop MD5 because that's what the older Postgres versions support - unless they also support SHA256 and just allowed MD5 usage.

**Comment by xach** [comment]
Ironclad is a big dependency. I have some standalone SHA256 code that I would be happy to contribute if it's wanted. It's not as fast as ironclad, but for authentication, I don't think it would be as critical as for other uses.

**Comment by phoe** [comment]
Sounds good - please post it somewhere. Do you have tests for it, or will they need to be written?

**Comment by xach** [comment]
I have some tests that may need some adaptation - it consists of a lot of random data and their expected SHA256 digests, and the test functions ensure that my code produces identical digests.

I'll put this up as soon as I can.

**Comment by sabracrolleton** [comment]
Before people get too excited, postgresql 12 still allows md5 authentication if that is how you set the configuration file. However, as people start to migrate to the more secure scram method, we need to support it.

**Comment by sabracrolleton** [comment]
It also is not just dropping in SHA256 support; it is also the SCRAM handshakes that will need to be added as well. There is a cl-scram project in quicklisp that does not seem to have been touched since 2015. I just reached out to the author to see if he was still interested in it.

**Comment by sabracrolleton** [comment]
On the subject of ironclad dependencies and size, my solution to the issue which is about to start more thorough testing uses the following functions from ironclad and cl-base64:

ironclad:ascii-string-to-byte-array
ironclad:hex-string-to-byte-array
ironclad:digest-sequence
ironclad:hmac-digest
ironclad:make-hmac
ironclad:update-hmac
ironclad:integer-to-octets
ironclad:octets-to-integer
ironclad:pbkdf2-hash-password

cl-base64:string-to-base64-string
cl-base64:base64-string-to-usb8-array
cl-base64:usb8-array-to-base64-string
 
Suggestions for for lighter dependencies are very welcome.

**Comment by sabracrolleton** [comment]
Resolved in latest commit
