### ISSUE TITLE
list-installed-extensions: build failure on SBCL

### ISSUE THREAD

**Issue by phoe** [marijnh/Postmodern#228]
https://github.com/marijnh/Postmodern/commit/baef8ebec5fa3d7321e1d0d51d977755bb5fc82a#commitcomment-38559280

> This new function [`list-installed-extensions`] is a duplicate in name and functionality to an existing one. It causes a duplicate definition failure in SBCL. http://report.quicklisp.org/2020-04-17/failure-report/postmodern.html#postmodern has a log.

**Comment by phoe** [comment]
The currently conflicting definitions:

https://github.com/marijnh/Postmodern/blob/baef8ebec5fa3d7321e1d0d51d977755bb5fc82a/postmodern/util.lisp#L762-L767

https://github.com/marijnh/Postmodern/blob/baef8ebec5fa3d7321e1d0d51d977755bb5fc82a/postmodern/util.lisp#L902-L904

**Comment by sabracrolleton** [comment]
Just the names. There are weeks I cannot do anything right. Thank you.
