### ISSUE TITLE
Behaviour of get-dao with keyword args

### ISSUE THREAD

**Issue by digikar99** [marijnh/Postmodern#230]
For a class

```lisp
(defclass points ()
  ((x :col-type integer :initarg :x
      :reader point-x)
   (y :col-type integer :initarg :y
      :reader point-y)
   (value :col-type integer :initarg :value
          :accessor value))
  (:metaclass dao-class)
  (:keys x y))
```

does `(get-dao 'points :x 0)` have a defined behaviour?

For example, with the instance 

```lisp
CL-USER> (insert-dao (make-instance 'points :x 0 :y 1 :value 10))
#<POINTS {101BA986F3}>
```

`(point-x (get-dao 'points :x 1))` results in 0 - which is not very obvious. Is the behavour defined or is this a bug in that this should raise an error?

**Comment by sabracrolleton** [comment]
Interesting question and daos are certainly not documented thoroughly and certainly not with multicolumn primary keys, so thank you for the callout. 

Looking at what you have done, you have created a class (and presumably defined a table) where the primary key is the set of x and y. So a multicolumn primary key. When calling (get-dao), you do not use keyword parameters. So when you called: 

`(get-dao 'points :x 1))`

That was the equivalent of an sql statement that said:

`select * from points where x = x and y = 0;`

The keyword parameter :x translated into the column name, resulting in a true statement for that part of the select query, but the second part of the select query y = 1 resulted in 1 match and returned a dao consisting of slots x, y and value with values of 0, 1 and 10 respectively.

The call to point-x on that dao returned the value that was in slot x, which was 0.

If you call:

`(get-dao 'points 0)`

 with only a single parameter when the primary key requires two, I get an error, which I would expect Does any of this make sense or am I missing your point (beside the fact that I need to document daos with multiple column primary keys)?

**Comment by digikar99** [comment]
Yes, that clears it up.

> That was the equivalent of an sql statement that said:
> 
> `select * from points where x = x and y = 0;`
> 
> The keyword parameter :x translated into the column name

I see; so, that's the translation. And if I also `(insert-dao (make-instance 'points :x 0 :y 0 :value 15))`, I get the first point for which the `where` part evaluated to true. Okay, that sums it up!

Also are there any downsides to directly documenting things in docstrings instead of maintaining a separate org file? For instance, I picked up the docstrings for [this](https://digikar99.github.io/common-lisp.readthedocs/postmodern/) but later discovered that docstrings are not as complete as the manual. So, if there are no downsides, I was thinking of issuing a PR with all the docs inside docstrings, and perhaps having a separate script do the extraction from the docstrings.

**Comment by sabracrolleton** [comment]
No downsides and I agree that the docstrings should keep up with the manual. Do you want to close the issue?

**Comment by digikar99** [comment]
Yup, the issue seems resolved.

**Comment by sabracrolleton** [comment]
Actually, let me modify my response on docstrings v. maintaining a separate org file. 

1. You can organize a separate org file. You cannot do that with docstrings.
2. Much easier to format examples in a separate written file than in a docstring.

**Comment by digikar99** [comment]
I see. Alright, I'll keep things as they are, and rather parse the org file instead. Thank you for your work!

**Comment by svantevonerichsen6906** [comment]
I certainly like to have both docstrings and a checked-in documentation file.  I believe that there are utilities to keep both in sync.

**Comment by phoe** [comment]
Somewhat off-topic: there are utilities such as [Staple](https://github.com/Shinmera/staple/) that are able to generate HTML documentation based on documentation strings as a form of synchronizing the two.

**Comment by digikar99** [comment]
Yes, but we do need to get the docstrings synced in first; but if it is easier to maintain org files rather than docstrings, may be we could go in reverse - parse the org-file and update the documentation strings of symbols appropriately. Not sure if there are utilities for that. 

Uhm, should this discussion to a separate issue?

**Comment by sabracrolleton** [comment]
I want to revist all the docstrings anyway (as well as ensure everything has docstrings), so will make everything consistent as part of that process.
