### ISSUE TITLE
Unable to use library using ABCL due to naming of get-pid function.

### ISSUE THREAD

**Issue by preetpalS** [marijnh/Postmodern#231]
When loading this library using ABCL, you run into the following error:

```
#<THREAD "interpreter" {4310A50E}>: Debugger invoked on condition of type PACKAGE-ERROR
  A symbol named GET-PID is already accessible in package COMMON-LISP-USER.
```

This is because **get-pid** is already defined in ABCL.

The error occurs after when running: `(use-package :postmodern)`

```
[1] CL-USER(2): (use-package :postmodern)

#<THREAD "interpreter" {198AF3F6}>: Debugger invoked on condition of type PACKAGE-ERROR
  A symbol named GET-PID is already accessible in package COMMON-LISP-USER.
Restarts:
  0: TOP-LEVEL Return to top level.
[1] CL-USER(3):
```

**Comment by phoe** [comment]
Do not `USE-PACKAGE` from inside `CL-USER`. The package `CL-USER` is allowed to contain any symbols predefined by the implementation, and so it does on ABCL.

Instead, do this:

```lisp
(defpackage #:pg-user
  (use #:common-lisp #:pgloader))

(in-package #:pgloader-user)
```

**Comment by preetpalS** [comment]
Thanks @phoe, I did not know that. I had a feeling I was doing something wrong.
