### ISSUE TITLE
Create-table error on multiple attributes

### ISSUE THREAD

**Issue by zmyrgel** [marijnh/Postmodern#236]
Taking example from documentation for creating tempory table:

```
S-SQL> 
(sql (:create-table (:temp :if-not-exists 'distributors-in-hell)
                    ((did :type (or integer db-null)))))
"CREATE TEMP TABLE if_not_exists (did INTEGER)"
S-SQL> 
(sql (:create-table (:unlogged :if-not-exists 'distributors-in-hell)
                    ((did :type (or integer db-null)))))
"CREATE UNLOGGED TABLE if_not_exists (did INTEGER)"
S-SQL> 
```

Creating temp table or unlogged table works but if also adding :if-not-exits to name form postmodern mistakes it as table name and ignores rest of form arguments.

Tested on latest quicklisp dists and sbcl 2.0.1 on openbsd/amd64

**Comment by sabracrolleton** [comment]
Thank you. Will fix.

**Comment by sabracrolleton** [comment]
Ok. The documentation is wrong. Buried in test-tables:

  (is (equal (sql (:create-table (:temp (:if-not-exists 'distributors-in-hell))
                                 ((did :type (or integer db-null)))))
             "CREATE TEMP TABLE IF NOT EXISTS distributors_in_hell (did INTEGER)"))

**Comment by sabracrolleton** [comment]
Fixed in new release v1.32.

**Comment by sabracrolleton** [comment]
I apologize. I will fix it so both ways will work.

**Comment by sabracrolleton** [comment]
Fixed in this mornings commit
