### ISSUE TITLE
Documentation Inconsistencies (version 1.32)

### ISSUE THREAD

**Issue by digikar99** [marijnh/Postmodern#241]
The dicussion is a continuation of https://github.com/cl-library-docs/common-lisp-libraries/pull/6.

***

Symbols external to package `:postmodern` but not found in doc: 

```
DATABASE-ERROR-DETAIL LIST-TEXT-SEARCH-CONFIG
 DATABASE-ERROR-MESSAGE DATABASE-ERROR-CAUSE
 CREATE-TABLESPACE GET-TABLE-OID
 DATABASE-ERROR-QUERY REGISTER-SQL-OPERATORS
 POSTGRES-ARRAY-STRING-TO-ARRAY DOCUMENT-DATABASE DATABASE-VERSION REAL
 GET-TABLE-COMMENT DATABASE-ERROR-CODE
```

Symbols found in doc but not external to package `:postmodern`:

```
ABORT-LOGICAL-TRANSACTION TABLE-DESCRIPTION-PLUS SERIAL SERIAL8
```

Minor:

1. ` *ISOLATION-LEVEL*` (doc) - Absence of "Variable" before the term
2. `SPLIT-FULLY-QUALIFIED-TABLENAME` (package) vs `SPLIT-FULLY-QUALIFIED-TABLE-NAME` (doc)
3. `LIST-PREPARED-STATEMENTS(&OPTIONAL` (doc) - a space is missing
4. `*TABLE-SYMBOL` (doc) - ending `*` is missing

**Comment by sabracrolleton** [comment]
Thank you. Will fix.

**Comment by sabracrolleton** [comment]
Fixed in this mornings commit
