### ISSUE TITLE
s-sql package lock issue breaks build

### ISSUE THREAD

**Issue by quicklisp** [marijnh/Postmodern#242]
http://report.quicklisp.org/2020-07-06/failure-report/postmodern.html#s-sql has the full log.

`Lock on package COMMON-LISP violated when defining REAL as a type specifier while in package S-SQL.`

**Comment by phoe** [comment]
https://github.com/marijnh/Postmodern/blob/ca1c8378c9497ca5018535ed288265d3e4bea1a4/s-sql/s-sql.lisp#L220-L221

The hotfix is to `:shadow #:real` in `defpackage s-sql` but that will then break all packages which `:use :s-sql` without shadowing importa.

An IMO better option is to create a new package `s-sql.types` with an empty `:use` list and define these types inside it. People will then be able to use those using package-local nicknames or via the full package name.

**Comment by sabracrolleton** [comment]
Reverted that change. (We have lived without this deftype since postmodern began.) Will think about phoe's suggestion or whether we have any use for this at all. Xach, does this at least temporarily resolve the problem?

**Comment by quicklisp** [comment]
Works for me!

**Comment by sabracrolleton** [comment]
Good.
