### ISSUE TITLE
ABCL does not handle characters > 1 byte

### ISSUE THREAD

**Issue by PiotrWasik** [marijnh/Postmodern#258]
It is a known issue mentioned on the main page, but just documenting it:

(query (format nil "select '~a'" (code-char 378)))

gives:

The value 378 is not of type (UNSIGNED-BYTE 8).
   [Condition of type SIMPLE-TYPE-ERROR]
Backtrace:
 0: (#<FUNCTION {192470C5}> #<SIMPLE-TYPE-ERROR {714177B8}> #<FUNCTION {6FD382F2}>)
 1: (#<FUNCTION {6FD382F2}> #<SIMPLE-TYPE-ERROR {714177B8}> #<FUNCTION {6FD382F2}>)
 2: (APPLY #<FUNCTION {6FD382F2}> (#<SIMPLE-TYPE-ERROR {714177B8}> #<FUNCTION {6FD382F2}>))
 3: (SYSTEM::RUN-HOOK SYSTEM::*INVOKE-DEBUGGER-HOOK* #<SIMPLE-TYPE-ERROR {714177B8}> #<FUNCTION {6FD382F2}>)
 4: (INVOKE-DEBUGGER #<SIMPLE-TYPE-ERROR {714177B8}>)
 5: (ERROR SIMPLE-TYPE-ERROR :DATUM 378 :EXPECTED-TYPE (UNSIGNED-BYTE 8))
 6: (SYSTEM:REQUIRE-TYPE 378 (UNSIGNED-BYTE 8))
 7: (WRITE-BYTE 378 #<TWO-WAY-STREAM {50C3D9D4}>)
 8: (CL-POSTGRES::SEND-QUERY #<TWO-WAY-STREAM {50C3D9D4}> "select 'ź'" CL-POSTGRES:LIST-ROW-READER)
....

**Comment by phoe** [comment]
This is not the case with ABCL but with Java; the JVM needs to be run with Unicode enabled.

Counterexample from my machine:

```lisp
$ java -jar abcl.jar 
Armed Bear Common Lisp 1.6.0
Java 15.0.1 Debian
OpenJDK 64-Bit Server VM
Low-level initialization completed in 0.283 seconds.
Startup completed in 1.645 seconds.
Type ":help" for a list of available commands.
CL-USER(1): (code-char 378)
#\ź
CL-USER(2): 
```

**Comment by PiotrWasik** [comment]
I can evaluate the code-char as well:
(code-char 378)
#\ź
The error I pasted above is signalled inside WRITE-BYTE

**Comment by phoe** [comment]
`write-byte` on a stream of `(unsigned-byte 8)`s requires to receive an `(unsigned-byte 8)`.

This means that you need to convert this character into multiple bytes. Perhaps via [babel](https://github.com/cl-babel/babel).

Also: 
```lisp
7: (WRITE-BYTE 378 #<TWO-WAY-STREAM {50C3D9D4}>)
```
What type is this stream? Is it bivalent (so both character and byte)?

**Comment by sabracrolleton** [comment]
Fixed in a commit this morning.
