### ISSUE TITLE
git tagging breaks to follow pattern

### ISSUE THREAD

**Issue by Hellseher** [marijnh/Postmodern#259]
Hi,

I would like to repack Postmodern for GUIX project. I just want to confirm which is the right way of git tags applied in your project?

```
git tag --list | sort -rn
1.32.4
1.30
v1.32.3
v1.32.2
v1.32.1
v1.32
v1.19
v1.18
v1.17
v1.16
v1.15
v1.14
```

I see the `v` prefix was dropped 2 times not consequently.

**Comment by sabracrolleton** [comment]
Thank you for flagging this. v1.32.5 is now the latest release.

**Comment by sabracrolleton** [comment]
Correction v1.32.6 is now the latest release
