### ISSUE TITLE
to-sql-string calls the deprecated write-rational-as-floating-point

### ISSUE THREAD

**Issue by attila-lendvai** [marijnh/Postmodern#263]
...as opposed to `write-ratio-as-floating-point`.

is that intentional? if so, then why was `write-ratio-as-floating-point` added at all?

or is the switching over scheduled for the future, as a potentially backwards incompatible change?

**Comment by sabracrolleton** [comment]
As I recall, a couple of people wanted one name, a couple wanted the other name. I do not care and as a potential backwards incompatible change to downstream, I have no issue leaving it in and removing the "deprecated" notation.

**Comment by sabracrolleton** [comment]
Happy for you to patch to-sql-string whichever way you prefer.

**Comment by attila-lendvai** [comment]
do you mean to open a PR? i'm not coding much in CL nowadays, therefore i'd prefer to leave it to someone who does and can properly test things.

i suggest to use the `write-ratio-as-floating-point` name. the reasoning: it's called from a single place that dispatches on the ratio type.

i see no reason to keep including the other one. there are no calls to it from inside the project, and it's not an exported function.

don't forget to also remove the tests.

**Comment by sabracrolleton** [comment]
Done
