### ISSUE TITLE
vector-row-reader with query?

### ISSUE THREAD

**Issue by Symbolics** [marijnh/Postmodern#272]
Is there a way to use [vector-row-reader](https://github.com/marijnh/Postmodern/blob/cdceb277711273be907b808603596c19bc5babd8/cl-postgres/public.lisp#L435) with [query](https://github.com/marijnh/Postmodern/blob/cdceb277711273be907b808603596c19bc5babd8/postmodern/query.lisp#L137)? This reader is not in the [results-style](https://github.com/marijnh/Postmodern/blob/cdceb277711273be907b808603596c19bc5babd8/postmodern/query.lisp#L64) list, so this is more of a question on usage.

I have some large result sets that I wish to work with, and the `vector-row-reader` seems like the best choice of the existing readers. `CL-postgres` is a low-level interface, and whilst it would work for this use-case, I'd rather deal with S-SQL and the higher level Postmodern functions.

Is there a reason `vector-row-reader` isn't available in `query`? It seems it would be simple enough to add, and I'll do that if it's the best way forward. I'm wondering though if there is some other usage pattern I'm missing for getting back results in vector/array format rather than list-of-lists, vector-of-hash, etc.

I'm moving data backwards and forwards from Postgres and a column oriented internal data structure, so ideally I'd be able to get a vector of columns, or an alist with cons like (column-name . vector-of-column-data). Any ideas on how to do this efficiently? A vector of vector-rows is still better than lists, but I still haven't quite worked out how to return a vector of vector-columns.

**Comment by sabracrolleton** [comment]
I do not recall any reason why it is not available.I cannot get to it this week but feel free to try it yourself. 

Is your column oriented internal data structure like a matrix?

**Comment by Symbolics** [comment]
It's treated like a matrix by many functions. Internally it's implemented as a vector of column-vectors, so the closer to a column format I can get the less churning I have to do with transposing rows/columns. With an upper bound of perhaps 50GB, this could be significant.

It occurs to me that perhaps I could write the results into a table (view?) and then loop over each column with a `SELECT *`. Not sure how efficient that would be on the database side, but Postgres is likely to have had a lot more optimisation than my code, so if I'm going to do inefficient operations, I'd rather do it there.

**Comment by sabracrolleton** [comment]
I managed to include it in some binary-parameter work that should get commited this weekend. Tests look good. It will return a vector of vectors, each row result being its own vector. 

If I understand you correctly, you need the table to be pivoted before you get the results. Assuming you are using Postgresql version 9.1 or later, there is a crosstab function in the optional tablefunc module that will pivot the table before it returns the results. I think that would get you your vector of column-vectors so you do not have to try to massage it in CL. 

You can take a look at this article and see if you think it would help you. https://learnsql.com/blog/creating-pivot-tables-in-postgresql-using-the-crosstab-function/

**Comment by Symbolics** [comment]
It looks like the pivot functions are just what I'm looking for. Thank you.

**Comment by Symbolics** [comment]
It looks like the pivot functions are just what I'm looking for. Thank you.

**Comment by Symbolics** [comment]
Did the vector-row-reader make it into the master branch?

**Comment by sabracrolleton** [comment]
Will be there later today.

**Comment by sabracrolleton** [comment]
Just merged in with the optional binary parameters commit.

**Comment by sabracrolleton** [comment]
And we are now looking at reverting that for other reasons. You can take a look at the vectors stuff in my fork. It is relatively straight forward; the only thing to note is that it returns an empty vector (not nil) if there are no rows matching the query. This is to keep it consistent with the behavior of :array-hash.

**Comment by sabracrolleton** [comment]
Merged back in

**Comment by nathanvy** [comment]
Somewhat on this topic, [here is a function I wrote](https://github.com/Lisp-Stat/data-frame/issues/28#issuecomment-2205195007) to get the row-major results set that postmodern returns into the column-major format that the `data-frame` library requires.

Do you know if there's a more performant way to do this, perhaps getting postgres to return the columns as rows?  I've read the article on pivoting and am familiar with pivot tables from excel but unless I'm missing something I don't think pivoting will do quite what I need.

My suspicion is that since SQL is fundamentally row-based there's not really a better alternative, am I wrong?
