### ISSUE TITLE
Consider adding retry-transaction restart.

### ISSUE THREAD

**Issue by sirherrbatka** [marijnh/Postmodern#293]
Hi. Postgres database error 40001 calls for retrying the transaction. I think that this would justify adding restart-case into call-with-transaction with retry-transaction restart. What do you think?

**Comment by sabracrolleton** [comment]
Sounds like a good idea. Do you want to submit a pull request?

**Comment by sirherrbatka** [comment]
I will do that.

**Comment by sabracrolleton** [comment]
I have committed the PR but I do want to flag the change in return value behavior by using tagbody. 

Pre PR, call-with-transaction returned the result of the (funcall body transaction) statement. 

Post PR call-with-transaction will return NIL. 

I do not have a feeling for whether this will be a breaking change for users or not.

**Comment by sirherrbatka** [comment]
I've missed this detail, and it is a fairly easy fix as well. I will open a pull request.
