### ISSUE TITLE
Feature request: add handling for FILTER to S-SQL

### ISSUE THREAD

**Issue by sirherrbatka** [marijnh/Postmodern#300]
It is present in PG for ages now and it is rather useful 
https://kb.objectrocket.com/postgresql/how-to-use-the-filter-clause-in-postgresql-881

**Comment by sabracrolleton** [comment]
You mean like:

    (query (:select (:as (:count '* :distinct) 'unfiltered)
                  (:as (:count '* :filter (:= 1 'bid)) 'filtered)
                  :from 'testtable))

translates to

    SELECT COUNT(DISTINCT *) AS unfiltered, COUNT(*) FILTER (WHERE (1 = bid)) AS filtered FROM testtable

You can see examples of its use at https://marijnhaverbeke.nl/postmodern/s-sql.html by searching for :filter

Do you have a use case which does not work?

**Comment by sirherrbatka** [comment]
No, I simply missed this feature already here. Sorry about that.
