### ISSUE TITLE
Embedded PostgreSQL in Common Lisp

### ISSUE THREAD

**Issue by snunez1** [marijnh/Postmodern#302]
I've been using SQLite as an embedded database for a while now, and its proven to be a good fit for the use case.  However, we need to move beyond its capabilities. CFFI and the sqlite shared library is already 'scary' enough for users to setup that we're leaning toward an installer to remove that part of the installation process.  Managing the installation and configuration of a PostgreSQL server instance would be a great deal more work and we'd like find a way to 'embed' it into a Common Lisp application.

Searching Google for 'embedded postgresql' turns up a number of projects in other languages that have embedded PostgreSQL ([go](https://github.com/fergusstrange/embedded-postgres), [java](https://github.com/zonkyio/embedded-postgres), [haskell](https://hackage.haskell.org/package/postgres-embedded-0.2.0/docs/Database-PostgreSQL-Embedded.html), et. al.) There are also trade magazines also [covering the topic](https://www.infoworld.com/article/3655953/postgres-everywhere.html).

 I thought this would be a good place to ask: What would it take to 'embed' PostgreSQL in Common Lisp?  This might be a multi-stage process over time.  The first problem to solve is installation, and then getting rid of stop/start the server, even if it initially runs out-of-process.

Any thoughts from the experts here?

**Comment by hraban** [comment]
Just wanted to chime and say I'm always surprised this isn't a native libpq feature. Sorry to offer no insight whatsoever :)

**Comment by sabracrolleton** [comment]
It is beyond my available time (and expertise). A few thoughts off the top of my head while acknowledging I am beyond my subject matter expertise.

Are you talking about embedding PostgreSQL into (1) an implementation of Common Lisp or (2) into an application that you have written in Common Lisp? I assume you are really talking about (2). 

Permissions can be messy (see, for example, the root user problems discussed by the go team at https://github.com/fergusstrange/embedded-postgres/issues/95). 

If you have multiple applications doing this, you presumably have multiple embedded postgresql databases. If so, you need to ensure that they are listening to different sockets, ip addresses or ports. I think running the applications and the embedded postgresql binary in separate docker containers would solve this.

I see that a node team has a project to spawn PostgresQL clusters programatically which might provide ideas for additional approaches. https://github.com/leinelissen/embedded-postgres.

**Comment by sabracrolleton** [comment]
Since we have had deafening silence, I am closing this request.
