### ISSUE TITLE
POMO function for extracting query from s-sql:sql ?

### ISSUE THREAD

**Issue by snunez1** [marijnh/Postmodern#304]
I'm thinking of using S-SQL to feed SQLite.  This looks easy except for the fact that a string kind of list is returned.  From the documentation:

```
(sql (:select '* :from 'country :where (:= 'a 1)))

 "(SELECT * FROM country WHERE (a = 1))"
```
I could remove the '(', but figure that POMO must have a built in way of doing this before passing the string to PostgreSQL.  I looked, but couldn't find it.

Where are the parenthesis striped out from these strings?

**Comment by sabracrolleton** [comment]
They are not stripped. Postgresql is quite happy with the parentheses.
