### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [marijnh/Postmodern#315]
Building with SBCL 2.2.10.127-d9429f05a / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 9f1af3951b938c159763018eddbdb0ca347b902a

*cl-postgres/simple-date-tests* fails to build because of a failure in  _simple-date/postgres-glue_.

*simple-date/postgres-glue* fails to build with the following error:

```
Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {10016D0003}>: The loader tried loading the symbol named TO-S-SQL-STRING into the package named S-SQL, but the package did not get defined, and does not exist.

```

[Full log here](http://report.quicklisp.org/2022-12-11/failure-report/postmodern.html)

**Comment by sabracrolleton** [comment]
Should be fixed now.
