### ISSUE TITLE
Ideas / feature requests

### ISSUE THREAD

**Issue by ankane** [marijnh/Postmodern#327]
Hi, big thanks for this project! I just started learning Lisp and it was super easy to use.

I put together [an example](https://github.com/pgvector/pgvector-lisp) for pgvector (an extension that adds vector similarity search to Postgres) and had a few ideas for features:

1. A `load-extension` function - `(:load-extension 'vector)`, similar to `load-uuid-extension`, which runs `CREATE EXTENSION IF NOT EXISTS "vector"`
2. `create-table` support for custom column types with a typmod, like `vector(3)` (you can currently use `(varchar 3)` to generate `VARCHAR(3)`, but I couldn't find a way to make it work with a custom type)
3. `create-index` support for [opclasses](https://www.postgresql.org/docs/current/gin-builtin-opclasses.html) - `CREATE INDEX ON items USING gin (metadata jsonb_path_ops)`
4. `create-index` support for [storage parameters](https://www.postgresql.org/docs/current/sql-createindex.html#SQL-CREATEINDEX-STORAGE-PARAMETERS) - `CREATE INDEX ON items (name) WITH (fillfactor=50)`
5. Include distance operators by default, like `<->`, `<#>`, and `<=>` ([PostGIS](https://postgis.net/docs/reference.html#operators-distance), [cube](https://www.postgresql.org/docs/current/cube.html#CUBE-OPERATORS-TABLE)) - this is currently possible with `(register-sql-operators :2+-ary :<-> :<#> :<=>)`

**Comment by sabracrolleton** [comment]
For 2, what you are looking for is adding additional methods to the generic method sql-type-name in the s-sql.lisp file. 

I am reluctant to call the type VECTOR (would prefer PGVECTOR) because of the potential for confusing this with a CL vector (a one dimensional array).

**Comment by sabracrolleton** [comment]
That is the advantage of having s-sql:sql-type-name as a generic function (and the reason it is exported). In your own code, you can add an appropriate method for your custom type. In this example I will just define a method for pgvector with a fallback default:

    (defmethod s-sql:sql-type-name ((lisp-type (eql 'pgvector)) &rest args)
                     (cond (args (format nil "VECTOR(~A)" (car args)))
                           (t "VECTOR(1)")))

This will then allow you to call :create-table with the appropriate result. The following example uses pomo:sql to show what the sql statement will look like:

    (pomo:sql (:create-table 'items ((id :type bigserial :primary-key t)
                                     (embedding :type (pgvector 3)))))
    "CREATE TABLE items (id BIGSERIAL NOT NULL PRIMARY KEY , embedding VECTOR(3) NOT NULL)"

Just to show the fallback situation, if for some reason you did not provide the numeric parameter:

    (pomo:sql (:create-table 'items ((id :type bigserial :primary-key t)
                                     (embedding :type (pgvector)))))
    "CREATE TABLE items (id BIGSERIAL NOT NULL PRIMARY KEY , embedding VECTOR(1) NOT NULL)"

You can create new methods for sql-type-name for as complicated custom types as you desire, you just need to decide what the format string should look like. Does that get you what you want?

**Comment by ankane** [comment]
Thanks @sabracrolleton, that seems to work. I think it'd nice for the generic function to do it by default (treating additional arguments as a typmod rather than dropping them).

```
(colname :type foo) -> FOO
(colname :type (foo 3)) -> FOO(3)
(colname :type (foo 2 3)) -> FOO(2,3)
```

**Comment by sabracrolleton** [comment]
Looking back at the code, sql-type-name is indirectly used in a couple of different contexts, one of which can conflict with your request on the default method. I will need to take more time testing to ensure I do not create more problems than I solve. The rest of your enhancement requests I should be able to get done this weekend.

**Comment by ankane** [comment]
Awesome, thanks @sabracrolleton!

**Comment by sabracrolleton** [comment]
Progress report. I have the requested functionality, but I am not thrilled with the first version of the s-sql syntax on the opclass support, particularly when mixing:
-  expressions (e.g. (:lower some-field-name); 
- postfix opclasses (e.g. (some-field-name :jsonb-path-ops).  and
- prefix opclasses (e.g. (:->> some-field-name some-value), (:to-tsvector 'english' some-field-name), (:box location location),  etc).

So might be another week depending on my workweek. On the upside, there will be extensive examples in the additional documentation as well as around 100 more tests.

**Comment by sabracrolleton** [comment]
Committed

**Comment by ankane** [comment]
Awesome, big thanks @sabracrolleton!

For 1, it looks like `load-extension` was added to the docs, but not the code. Submitted a PR in #330.

**Comment by sabracrolleton** [comment]
Arrgh. That was embarrassing.
