### ISSUE TITLE
export begin-transaction symbol

### ISSUE THREAD

**Issue by t-zuehlsdorff** [marijnh/Postmodern#334]
Aloha,

i tried to port some Unit-Tests which test various queries against a PostgreSQL database.

While writing the tests, i realized that the begin-transaction function is not exported.

I can't use the with-transaction macro, because i *never* want anything of my tests to be persisted at all. The test should be executed within a transaction and when they are done, the transaction must be rollback'ed.

Can you export the begin-transaction symbol so we can realize this scenario?

Thank you very much,
Torsten

**Comment by sabracrolleton** [comment]
Thank you for bringing this up. Done.

**Comment by t-zuehlsdorff** [comment]
Thank you very much for the fast resolution :)
