### ISSUE TITLE
CL-POSTGRES-TRIVIAL-UTF-8:UTF-8-DECODING-ERROR {10084930F3}

### ISSUE THREAD

**Issue by JosefMachytkaNetApp** [marijnh/Postmodern#340]
Hi good people, maybe you can help me.

I am using pgloader to copy data from foreign tables (source is Sybase ASE 16) created by tds_fdw extension, into target PostgreSQL local tables. In PostgreSQL all works as expected. I can select data from FDW table, I can do `INSERT INTO target_table SELECT * FROM fdw_table`, all works. But when I start pgloader to copy data from all tables, it fails on some tables with an error message - "A thread failed with error: Invalid byte at start of character: 0xFC" - or other 0x.. code

Error is reported in the CL-POSTGRES-TRIVIAL-UTF-8 - which seems to be maintained by you.

```
2024-02-23T08:34:24.097092Z ERROR A thread failed with error: Invalid byte at start of character: 0xFC
2024-02-23T08:34:24.101092Z ERROR Date/time: 2024-02-23-09:34!
An unhandled error condition has been signalled:
   Invalid byte at start of character: 0xFC

Backtrace for: #<SB-THREAD:THREAD "lparallel" RUNNING {10059F0073}>
0: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE-TO-STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {1008493303}>)
1: (TRIVIAL-BACKTRACE:PRINT-BACKTRACE #<CL-POSTGRES-TRIVIAL-UTF-8:UTF-8-DECODING-ERROR {10084930F3}> :OUTPUT NIL :IF-EXISTS :APPEND :VERBOSE NIL)
2: ((LAMBDA (CONDITION) :IN PGLOADER.LOAD:COPY-FROM) #<CL-POSTGRES-TRIVIAL-UTF-8:UTF-8-DECODING-ERROR {10084930F3}>)
3: (LPARALLEL.KERNEL::CONDITION-HANDLER #<CL-POSTGRES-TRIVIAL-UTF-8:UTF-8-DECODING-ERROR {10084930F3}>)
4: (SB-KERNEL::%SIGNAL #<CL-POSTGRES-TRIVIAL-UTF-8:UTF-8-DECODING-ERROR {10084930F3}>)
5: (ERROR CL-POSTGRES-TRIVIAL-UTF-8:UTF-8-DECODING-ERROR :BYTE 252 :MESSAGE "Invalid byte at start of character: 0x~X")
6: (CL-POSTGRES-TRIVIAL-UTF-8:READ-UTF-8-STRING #<unavailable argument> :NULL-TERMINATED #<unavailable argument> :STOP-AT-EOF #<unavailable argument> :CHAR-LENGTH #<unavailable argument> :BYTE-LENGTH #<unavailab
le argument>)
7: ((LAMBDA (#:G0 #:G1) :IN "/usr/share/common-lisp/source/postmodern/cl-postgres/interpret.lisp") #<SB-SYS:FD-STREAM for "socket, peer: /var/run/postgresql/.s.PGSQL.5432" {1007EED623}> 540)
8: ((LAMBDA (#:G39 PGLOADER.SOURCES:FIELDS) :IN PGLOADER.SOURCES:MAP-ROWS) #<SB-SYS:FD-STREAM for "socket, peer: /var/run/postgresql/.s.PGSQL.5432" {1007EED623}> #(#<CL-POSTGRES::FIELD-DESCRIPTION {1007F0AD63}> 
#<CL-POSTGRES::FIELD-DESCRIPTION {1007F0AF13}> #<CL-POSTGRES::FIELD-DESCRIPTION {1007F0B0C3}> #<CL-POSTGRES::FIELD-DESCRIPTION {1007F0B273}> #<CL-POSTGRES::FIELD-DESCRIPTION {1007F0B423}> #<CL-POSTGRES::FIELD-DE
SCRIPTION {1007F0B5D3}> #<CL-POSTGRES::FIELD-DESCRIPTION {1007F0B783}>))
9: (CL-POSTGRES::SEND-QUERY #<SB-SYS:FD-STREAM for "socket, peer: /var/run/postgresql/.s.PGSQL.5432" {1007EED623}> #<unavailable argument> #<unavailable argument>)
10: ((LABELS #:G4 :IN CL-POSTGRES:EXEC-QUERY))
11: ((:METHOD PGLOADER.SOURCES:MAP-ROWS (PGLOADER.SOURCE.PGSQL:COPY-PGSQL)) #<PGLOADER.SOURCE.PGSQL:COPY-PGSQL {1005D33833}> :PROCESS-ROW-FN #<FUNCTION (LAMBDA (PGLOADER.LOAD::ROW) :IN PGLOADER.LOAD:QUEUE-RAW-DA
TA) {1007EEBD0B}>) [fast-method]
```

Underlying database should be in UTF-8 according to the content of Sybase sys tables. But it looks like some data could be in UTF-16. 

I tried to configure FreeTDS to convert UTF-16 to UTF-8 but it is unclear if this conversion really works in FreeTDS version 5.0 which is necessary for Sybase. Docu mentions it only for version 7+.

It is really confusing for me that on PostgreSQL level all works but this common lisp library is throwing an error. This problem is now serious blocker for migrations. Could you give me at least some advise?

I already tried many different recipes from web, none of them worked.

Thank you very much.

----

During additional tests I see code failing both with error message on the line 108 - https://github.com/marijnh/Postmodern/blob/master/cl-postgres/trivial-utf-8.lisp#L108 and on the line 135 - https://github.com/marijnh/Postmodern/blob/master/cl-postgres/trivial-utf-8.lisp#L135

I wrote short python script which reads data from those tables and checks if they can be interpreted as UTF-8 string - all works. I also checked repeatedly data in PostgreSQL, strings look absolutely correct, tds_fdw and PostgreSQL can handle them without any problems.

**Comment by sabracrolleton** [comment]
Hmm. It certainly looks like cl-postgres-trivial-utf-8 THINKS it is getting a utf-16 encoded string coming from the database. At that point it errors out because it was only written to handle ascii and utf-8. 

I will take a look, but I cannot promise a quick fix.

**Comment by svantevonerichsen6906** [comment]
An `#xFC` byte in UTF-16 would be part of some arabic ligature if I see that right, but maybe that's just what it is.  On the other hand, maybe it's some binary data, maybe it's compressed?

**Comment by sabracrolleton** [comment]
What operating system are you using?

**Comment by sabracrolleton** [comment]
Can you post your python script? Since we do not have access the the data triggering the error in cl-postgres, I would like to set up some kind of test base that passes on the python side and fails on the common lisp side.

**Comment by JosefMachytkaNetApp** [comment]
Hi, here are details:

* OS: Debian GNU/Linux 12 (bookworm)

* Installed packages for connection to Sybase:
ii  freetds-bin                     1.3.17+ds-2                         amd64        FreeTDS command-line utilities
ii  freetds-common                  1.3.17+ds-2                         all          configuration files for FreeTDS SQL client libraries
ii  freetds-dev                     1.3.17+ds-2                         amd64        MS SQL and Sybase client library (static libs and headers)
ii  postgresql-16-tds-fdw           2.0.3-3.pgdg120+1                   amd64        PostgreSQL foreign data wrapper for TDS databases
ii  tdsodbc:amd64                   1.3.17+ds-2                         amd64        ODBC driver for connecting to MS SQL and Sybase SQL servers

- FreeTDS configured to version 5.0 which seems to be the proper version for Sybase. Unfortunately it looks advanced options are available only for 7+

- my python script is quite long, testing different topics, so just shortly:
  - uses pyodbc library to connect to Sybase
  - calls pyodbc.connect with driver "FreeTDS"
  - opens cursor, executes "select * from table"
  - fetches all rows, checks row by row, finds string columns, tries their content with column.encode('utf8').decode('utf8') if it does not fail
  
But after some tests I think pyodbc library already does the trick and converts strings into UTF8, so in other steps all works as expected.

But I am trying something different now - I found that pgloader parallel workers are spoiling error messages from the crashed threads. So I am testing now just with single worker and checking output from crash. It gives now much more information. I will post details if I find something interesting.

**Comment by JosefMachytkaNetApp** [comment]
Unfortunately my attempts to catch problematic data in one specific table using only single worker and very low prefetch rows number was not successful. It looks like error message from the crash does not show problematic row content - just hundreds of "0"s. But looking at the content of that table, there is a column "value" of the Sybase data type "text", which according to SAP docu should be able to store up to 2GB of "printable characters". On the other hand Sybase has special command "writetext" for inserts and updates into this type of columns. So question is what it really stores internally.

When I look into its content, it contains what ever you can image, because it stores configuration properties of all types. There are:
- XML documents, some of them quite huge - <?xml version="1.0" encoding="ISO-8859-1"?>
- some hexa tokens
- Certificates of different types
- json or similarly looking chains for email configuration etc.
- something which could be some compressed data

Beside of "text" data type, Sybase also has "unitext" data type, which is dedicated for "Unicode characters", so that "text" data type will most likely use different character sets, but so far I did not find any info how to check which one is really used.

**Comment by sabracrolleton** [comment]
I am still trying to figure out what valid byte sequence might be causing the problem.

Another side note: If you look at https://www.postgresql.org/docs/current/multibyte.html, postgresql itself does not support utf-16. You can prove this yourself doing the following:

## 1. Create utf8 csv file

```bash
echo ÄÖÜÈäes8 > utf8.csv
```

Verify that it is utf8

```bash
file -i utf8.csv

utf8.csv: text/plain; charset=utf-8
```

## 2. Create utf16 csv file

Take the utf8 file, use iconv to convert it to utf-16 as a new file

```bash
iconv -f UTF-8 -t UTF-16 utf8.csv -o utf16.csv
```

Verify that it is utf16

```bash
file -i utf16.csv

utf16.csv: text/plain; charset=utf-16le
```

## 3. Start psql

## 4. Create utf8 database
Replace "sabra" with the user of your choice.

```sql
CREATE DATABASE "test8"
WITH OWNER "sabra"
ENCODING 'UTF8'
```

## 5. Now switch to the test8 database

```sql
\c test8
```

## 6. Create 2 tables

```sql
create table test8 (data text);
create table test16 (data text);
```

## 7. Use postgresql copy command to insert the utf8 file into the proper table

```sql
\copy test8 from '/home/sabra/tmp/utf8.csv' delimiter ',' csv;
```

Validate that the data got in and you can see it:
```sql
select * from test8;

  data   
----------
 ÄÖÜÈäes8
(1 row)

```


## 8. Now try the same thing with the utf16 file

```sql
    \copy test16 from '/home/sabra/tmp/utf16.csv' delimiter ',' csv;
ERROR:  invalid byte sequence for encoding "UTF8": 0xff
CONTEXT:  COPY test16, line 1
```

Postgresql will not import the utf-16 file.

**Comment by JosefMachytkaNetApp** [comment]
Thank you for that example. 
Can I somehow debug your function using some Lisp code to catch problematic data? 
I tried `pgloader -d` but in debug messages from crash I somehow do not see anything useful.

**Comment by sabracrolleton** [comment]
I have never used pgloader, so I am just guessing here.

If you build pgloader from source, does it create a directory ~/quicklisp/dists/quicklisp/software/ ? If so, you are looking for a subdirectory named postmodern-xxx.git/cl-postgres/ where the xxx is some date. The file you would be looking for would be trivial-utf-8.lisp and strings-utf-8.lisp. Then you would have to rebuild pgloader from source and it should pick up changes you make to those files.

If pgloader does not create that directory, I do not know where it might stash source files. 

Someone else might know how you can keep the lisp instance that pgload creates running so you can connect to it and recompile the lisp functions on the fly.

**Comment by JosefMachytkaNetApp** [comment]
Hi, looks like I found it - that table is probably storing data in plain ASCII. I did some additional testing and debugging and in one moment Sybase gave me suddenly an error `ASE is now using a multi-byte character set, and the TEXT character counts have not been re-calculated using this character set for table '....'. Use DBCC FIX_TEXT on this table`. So it looks like problem comes from older versions of Sybase. Your function seems to refuse ASCII codes of special German letters like ä or ü. Which is of course completely OK. And now I also see ASCII values of these characters in error messages from crashes. It is just a bit confusing for me that PostgreSQL somehow recognizes this problem and converts data properly - I will look at it too. So please wait with further actions until I find more. Thank you so far very much for your help. :1st_place_medal: :star: :superhero:

**Comment by sabracrolleton** [comment]
Plain ASCII is a subset of UTF-8. I am surprised that there is a problem.

**Comment by svantevonerichsen6906** [comment]
If it contains Umlauts, it's not ASCII, but probably something like ISO 8859-1 (a. k. a. latin-1) or some »Windows Codepage« (1274 or thereabouts IIRC).

**Comment by JosefMachytkaNetApp** [comment]
Yes, looks like it is latin-1. That was original default on very old versions of Sybase.

**Comment by JosefMachytkaNetApp** [comment]
I modified lisp code in the pgloader trivial-utf-8 file to not fail with errors but to just print warnings and built our own version of pgloader with this modification. Almost all rows with these "invalid byte" warnings are now accepted by PostgreSQL, just very few of them are rejected because content cannot be interpreted as UTF8 string. Pgloader with "on error resume next" setting skips there problematic rows and reports them into special log files and this seems to be a reasonable result for this use case. So I am closing this issue. Thank you.

**Comment by sabracrolleton** [comment]
That seems like the appropriate immediate fix and something that should be optional in the error conditioning handling for trivial-utf-8. Is there anything common in the problematic rows?

**Comment by JosefMachytkaNetApp** [comment]
In this use case all warnings are about special German letters encoded with Latin1. And rows rejected by PostgreSQL show one of these 2 errors:
Database error 22021: invalid byte sequence for encoding "UTF8": 0xf6 0xb2 0xb5 0xae
Database error 22021: invalid byte sequence for encoding "UTF8": 0xf6 0xb2 0xa4 0xa5
But only handful of rows out of millions were rejected so result is acceptable.

**Comment by sabracrolleton** [comment]
Thank you. I will think about the best fall-back option when the error gets triggered.
