### ISSUE TITLE
How to contribute to the docs?

### ISSUE THREAD

**Issue by kilianmh** [marijnh/Postmodern#342]
I got some ideas for a section about dao class inheritance. It looks like you are using org mode to generate the html, a setup which I do not use.
Should I give you the text/code in an issue, or do a PR with only the .org file changed?

**Comment by sabracrolleton** [comment]
You can give it to me as text in an issue and I will convert it org mode and then regenerate the html.

**Comment by sabracrolleton** [comment]
I probably will not get to it until late next week.

**Comment by sabracrolleton** [comment]
Done
