### ISSUE TITLE
Possible bug: primary-key value not compiled correctly

### ISSUE THREAD

**Issue by mmontone** [marijnh/Postmodern#353]
When I compile an SQL expression with `:primary-key` in `NIL`, I get an incorrect `PRIMARY KEY` sql output nonetheless.

```
DB> (s-sql:sql-compile '(:create-table my-table
                         ((id :type integer :primary-key t)
                          (non-primary :type string :primary-key nil))))
"CREATE TABLE my_table (id INTEGER NOT NULL PRIMARY KEY , non_primary TEXT NOT NULL PRIMARY KEY )"
```
I expect `PRIMARY KEY` not present for `non_primary` column.

I have to check with latest Postmodern yet, I'm using Quicklisp version.

**Comment by mmontone** [comment]
It also happens with latest Github version.

**Comment by mmontone** [comment]
I can prevent by not passing `:primary-key` , but docs mention I can pass with `NIL`. 
https://marijnhaverbeke.nl/postmodern/s-sql.html#sql-op-create-table

**Comment by svantevonerichsen6906** [comment]
I think I'd expect the same, `nil` being the same as the option not given.

The problem seems to be in s-sql.lisp, line 2178 (in function `expand-table-column`), where this should probably just be checked as another case:

```
((null value)
 '())
```

This should probably be the first clause, so that we can omit `and value` in the others.

**Comment by sabracrolleton** [comment]
Is someone going to submit a pull request?

**Comment by sabracrolleton** [comment]
Just committed @svantevonerichsen6906 's suggestion and fixed the relevant tests. Thank you both for identifying it and the suggested fix.

**Comment by mmontone** [comment]
Thanks for the fix!
