### ISSUE TITLE
Prepared statements unusable for the first time in a transaction?

### ISSUE THREAD

**Issue by myrkraverk** [marijnh/Postmodern#357]
Hi,

As far as I can tell, prepared statements are unusable for the first time inside transactions, because the function is hardcoded to drop a prepared statement that doesn't exist.  For the record, I'm using Quicklisp Postmodern, but code inspection indicates it's also a problem in GH.

This is how I reproduce it.
```
(connect-toplevel db nm pw hn :port 5432 :use-binary t)
(setf one-fn (prepare "select 1" :single))
(with-transaction () (funcall one-fn))
```
This results in a 25P02 error, because something previously inside the transaction failed [the aforementioned drop prepared statement].  Obviously, this works if I do the funcall outside a transaction, and also inside a transaction if I've done the funcall once prior.

Is this expected behaviour?  Or a way to fix it in client code?

**Comment by sabracrolleton** [comment]
Does the following work for you?

    (setf *allow-overwriting-prepared-statements* nil)

    (with-connection '(db nm pw hn)
        (defprepared 'dp1 "select 1" :single)
        (with-transaction () 
          (funcall 'dp1)))

**Comment by sabracrolleton** [comment]
Or, more similar to what you were doing:

    (setf *allow-overwriting-prepared-statements* nil)

    (with-connection *db*
        (let ((one-fn (prepare "select 1" :single)))
             (with-transaction ()
                  (funcall one-fn))))

**Comment by myrkraverk** [comment]
Yes, that is working for me; I never tested the workarounds from earlier, and as of commit #358 everything seems to be working fine.
