### ISSUE TITLE
String variables won't work for the database host.

### ISSUE THREAD

**Issue by dertuxmalwieder** [marijnh/Postmodern#359]
My code (the relevant parts):

```lisp
(defparameter *dbhost* "localhost")
;; user, dbname, port etc. go here...

;; ask for the database host:
(format t "Enter your PostgreSQL database host (defaults to '~a'): " *dbhost*)
(finish-output)
(let ((dbhost (str:trim (read-line))))
  (unless (str:emptyp dbhost) (setq *dbhost* dbhost)))

;; check the type of *dbhost*:
(print (type-of *dbhost*)).  ;; <-- this echoes (SIMPLE-ARRAY CHARACTER (9))

;; connect:
(postmodern:connect-toplevel *dbname* *dbuser* *dbpassword* *dbhost* :port *dbport* :use-ssl (if *dbssl* :yes :no))
```

The error message:

```
The value of CL-POSTGRES::DATABASE is DEMOAPP::*DBHOST*, which is not of type STRING.
```

Well, but it is, because a "string" **is** a `simple-array`. How do I fix this?

**Comment by xach** [comment]
It’s printing the value it gets, which is a symbol, not a string. Do you have a macro somewhere?On Dec 16, 2024, at 16:05, Cthulhux ***@***.***> wrote:﻿
My code (the relevant parts):
(defparameter *dbhost* "localhost")
;; user, dbname, port etc. go here...

;; ask for the database host:
(format t "Enter your PostgreSQL database host (defaults to '~a'): " *dbhost*)
(finish-output)
(let ((dbhost (str:trim (read-line))))
  (unless (str:emptyp dbhost) (setq *dbhost* dbhost)))

;; check the type of *dbhost*:
(print (type-of *dbhost*)).  ;; <-- this echoes (SIMPLE-ARRAY CHARACTER (9))

;; connect:
(postmodern:connect-toplevel *dbname* *dbuser* *dbpassword* *dbhost* :port *dbport* :use-ssl (if *dbssl* :yes :no))
The error message:
The value of CL-POSTGRES::DATABASE is DEMOAPP::*DBHOST*, which is not of type STRING.

Well, but it is, because a "string" is a simple-array. How do I fix this?

**Comment by dertuxmalwieder** [comment]
None I was aware of.

**Comment by dertuxmalwieder** [comment]
`setf` would probably be more elegant, yes. There was no good reason for that, thank you.

> what do you get if you print out the value of *dbhost* just before you call connect-toplevel?

I had, indeed, searched for the error in the wrong place / posted the wrong part of the code. I am deeply sorry - I spent too much time glaring at my own code, I'm afraid. I could narrow it down to a call to `with-connection` and `*dbname*` being a bad string, not `*dbhost*`:

```lisp
 (write-line "Before!")
 (print (type-of *dbname*))(terpri)
 (write-line *dbname*)
 (postmodern:with-connection '(*dbname* *dbuser* *dbpass* *dbhost* :port *dbport* :use-ssl (if *dbssl* :try :no))
     (write-line "It already broke here..")
     ;; any other code isn't relevant anymore, it threw a stack trace, see below
```

Output:

```
Before!

(SIMPLE-ARRAY CHARACTER (7))
mydatabase

debugger invoked on a SIMPLE-TYPE-ERROR @7003F433FC in thread
#<THREAD tid=259 "main thread" RUNNING {7009FA0003}>:
  The value of CL-POSTGRES::DATABASE is DEMOAPP::*DBNAME*, which is not of type STRING.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [STORE-VALUE] Supply a new value for CL-POSTGRES::DATABASE.
  1: [ABORT      ] Exit from the current thread.

(CL-POSTGRES:OPEN-DATABASE #<unavailable argument> DEMOAPP::*DBUSER* DEMOAPP::*DBPASS* DEMOAPP::*DBHOST* DEMOAPP::*DBPORT* (IF DEMOAPP::*DBSSL* :TRY :NO) "postgres" "" NIL)
   source: (CHECK-TYPE DATABASE STRING)
```

(I *think* I can "fix" this by just skipping the scoped connection here. For this use case, one global connection is enough. Still, I'm curious.)

**Comment by xach** [comment]
''(*dbname* *dbuser* *dbpass* *dbhost* :port *dbport* :use-ssl (if *dbssl*
:try :no)) evaluates to a bunch of symbols.

You want (list *dbname* *dbuser* *dbpass* *dbhost* :port *dbport* :use-ssl (
if *dbssl* :try :no)) instead.

**Comment by sabracrolleton** [comment]
And we have found the problem:

    (postmodern:with-connection '(*dbname* *dbuser* *dbpass* *dbhost* :port *dbport* :use-ssl (if *dbssl* :try :no))

Take a look at the character before the opening paren of the list of parameters. The single quote there means that lisp is not going to determine the value of the variable inside the list - you just have a list of symbol names.

Either use 

    (list *dbname* *dbuser* *dbpass* *dbhost* :port *dbport* :use-ssl (if *dbssl* :try :no))

or use a back-tick with commas to indicate that  you want the values of the variables.

    `(,*dbname* ,*dbuser* ,*dbpass* ,*dbhost* :port ,*dbport* :use-ssl ,(if *dbssl* :try :no))

**Comment by dertuxmalwieder** [comment]
Ah! Now that makes sense to me. Thank you!

Looks like I had been away from Lisp for too long. 🫣
