### ISSUE TITLE
Will it be possible to return hash tables?

### ISSUE THREAD

**Issue by isikfsc** [marijnh/Postmodern#65]
Will it be possible to return hash tables?

**Comment by slyrus** [comment]
Wanting a hash table, even one keyed on an integer, isn't entirely unreasonable, as it might be nice to have, e.g., an object/row's id as the hash table key. But, as marijnh points out, this is a great exercise for the OP. I suggest this issue be closed.

**Comment by slyrus** [comment]
I'm sure there are plenty of other of ways to do this, but something like this might work for you:

(cl-postgres:def-row-reader hash-table-row-reader (fields)
  (let ((row-hash (make-hash-table)))
    (loop :while (cl-postgres:next-row)
       :do (let ((first-field (elt fields 0)))
             (when first-field
               (let ((first-field-name (cl-postgres:field-name first-field))
                     (first-field-value (cl-postgres:next-field first-field)))
                 (setf (gethash first-field-value row-hash)
                       (let ((field-hash (make-hash-table)))
                         (setf (gethash first-field-name field-hash)
                               first-field-value)
                         (loop :for field :across (subseq fields 1)
                            :do (setf (gethash (cl-postgres:field-name field) field-hash)
                                      (cl-postgres:next-field field)))
                         field-hash))))))
    row-hash))
