### ISSUE TITLE
support for "ORDER BY" in aggregation with string_agg et al

### ISSUE THREAD

**Issue by tshatrov** [marijnh/Postmodern#68]
It should be possible to to reproduce this syntax with S-SQL:
http://www.postgresql.org/docs/9.1/static/sql-expressions.html#SYNTAX-AGGREGATES

`SELECT string_agg(a, ',' ORDER BY a) FROM table;`

`(:order-by (:string-agg 'a ",") 'a)` produces `(string_agg(a, E',') ORDER BY a)` which doesn't work. It doesn't seem to be possible to use this feature without resorting to :raw.

**Comment by sabracrolleton** [comment]
Now possible with commit from Jul 22 2018. See tests in s-sql for usage.
