### ISSUE TITLE
Problems with subqueries (IN, ANY, EXISTS, etc)

### ISSUE THREAD

**Issue by vityok** [marijnh/Postmodern#74]
There is no easy way to provide lists of values for subset queries. For example, if I want to select only those matches that have titles matching one of the given strings. If the given strings or their number is known in advance, I can do something like:

``` lisp
(pomo:query "SELECT match_id FROM match WHERE title IN ($1, $2)"
  "title1" "title2" :lists)
```

but it gets problematic once the list of titles is generated at the run-time. One of the workarounds could be like a solution to a similar [problem on Node.js](http://stackoverflow.com/a/11691651/2240219). But the problem here is that `pomo:query` is a macro and can not be passed to `apply`.

S-SQL query with a similar intention also fails:

```
(s-sql:sql (:SELECT 'match_id :FROM 'match :WHERE (:IN 'title '("b"))))
; Evaluation aborted on #<SIMPLE-ERROR "Value ~S can not be converted to an SQL literal." {CD183C9}>.
```

It would be very nice to be able to handle with such queries naturally.

Or am I missing something?

**Comment by marijnh** [comment]
Have you seen the [`:set`](http://marijnhaverbeke.nl/postmodern/s-sql.html#set) operator? I think you can use that here.

**Comment by vityok** [comment]
Hi Marijn,

Nope, but I already managed to find a work-around using `cl-postgres:prepare-query` and `cl-postgres:exec-prepared`. However, I've stuck into other issues with the query where this construct is used: it uses OFFSET, LIMIT, and ORDER BY clauses and I had troubles making S-SQL handle them all.

Thanks for your hint!
Victor

**Comment by sabracrolleton** [comment]
I know this is old, but this works on the sql question:

`(s-sql:sql (:SELECT 'match_id :FROM 'match :WHERE (:IN 'title (:set (list "b")))))`

using list instead of quote
