### ISSUE TITLE
cl-postgres is broken in latest version of Quicklisp

### ISSUE THREAD

**Issue by sebyte** [marijnh/Postmodern#90]
One or more of  slyrus' commits to interpret.lisp made since Sep 12 2016 breaks cl-postgres.

 https://github.com/marijnh/Postmodern/commits/master/cl-postgres/interpret.lisp

These commits have all found their way into the latest version of Quicklisp dist "quicklisp" (2016-09-29).

Rolling back to the latest version of "quicklisp" **but one** (2016-08-25) fixes the problem.

The error I was getting was:
```
CL-POSTGRES-TRIVIAL-UTF-8:UTF-8-DECODING-ERROR
Invalid byte at start of character: 0xB3
[...]
```
on a source file containing no unusual characters.

Unfortunately I do not have the skills required to debug the problem further.

**Comment by sebyte** [comment]
Doh!  Thanks.  Forgot to @-mention him.

Quoth Marijn Haverbeke <notifications@github.com>
on Thu, 06 Oct 2016 03:15:24 -0700:
> /cc @slyrus 

-- 
Dorothy Annan Trevor Tennant database - DATTdb
http://dattdb.info

**Comment by slyrus** [comment]
Hmm... sounds like we're getting a binary answer back that we're not expecting. @sebyte can you post a snippet of code with a query that breaks? It's not going to be the source file that's yielding the bogus character, but rather the stream of data coming back from the database.

**Comment by slyrus** [comment]
Forcing everything to be text would "fix" this, but at the cost of having the client unpack all of the data from the database, something I'd definitely like to avoid.

**Comment by sebyte** [comment]
I would post a snippet of code but I've no idea what the s/bogus/offending/ character might be.  The first query in the source file being loaded when things break returns a snapshot of the database as a whole.  (Although the volume of data returned is tiny as far as computers are concerned, it's large enough for me to reject to idea of inspecting every row).

Perhaps a `#'DEBUG` call added to `#'READ-UTF-8-STRING` featuring the `INPUT` argument is the way to go?

**Comment by slyrus** [comment]
It's not about the particular character, it's (probably) that postgres is returning a binary result when postmodern is expecting a text type, and we're trying to read that binary result as a UTF-8 string and failing. If you can provide a stack trace, and the corresponding query that's being executed when this breaks, that would be helpful. In the absence of that, I don't have much to go on.

**Comment by slyrus** [comment]
@sebyte are you using any complex (nested, etc...) queries, or relatively obscure column types? The rationale behind the changes that are now causing you problems is that we were returning the naive text representation for things like arrays, leaving the user the test of parsing and unpacking arrays, and other interesting data types, rather than getting binary data back from the database and putting that in the appropriate lisp data types.

**Comment by slyrus** [comment]
@sebyte The other thing that would be helpful would be to bisect the commits from c9747 and let me know which commit actually breaks your application.

**Comment by sebyte** [comment]
@slyrus: Here's a list of the distinct data types returned by queries
across all tables:

 boolean
 char(n)
 integer
 integer[]
 row()
 text
 timestamp without time zone
 varchar(n)

Perhaps the row() composite type is not being handled correctly?

Quoth Cyrus Harmon <notifications@github.com>
on Fri, 07 Oct 2016 20:00:30 -0700:
> @sebyte are you using any complex (nested, etc...) queries, or
> relatively obscure column types? [...]

-- 
Dorothy Annan Trevor Tennant database - DATTdb
http://dattdb.info

**Comment by slyrus** [comment]
Ok, this is helpful. Yes, it's most likely the row type, although the integer[] and the timestamp without time zone are also possible suspects. Can you give me the specifics of what's in the row() type?

**Comment by slyrus** [comment]
is it possible that you use time (not timestamp) somewhere?

**Comment by slyrus** [comment]
So it seems there are a couple of issues here. First, time, not timestamp, was broken. Are you using time? I can fix that, but the question is what should we do about simple-date? Should we add a time class to simple-date? Also, @marijnh I'd like your input on what to do about the fact that the cl-postgres tests seem to depend on simple-date being loaded, at least for the date/timestamp/etc... tests. Should we leave that as is or should we try to test the built-in stuff (without simple-date)?

**Comment by marijnh** [comment]
I think the simple-date tests serve as a useful way to test if defining/overriding types from external code is still working, but yeah, since this is all working by way of global state, that does make it hard to test other time deserializers. Maybe a kludge that involves creating a new copy of the default serializer table, and uses that during tests for default serializers, would work?

**Comment by slyrus** [comment]
That's probably a good idea, but testing the simple-date stuff is probably the most important. I've pushed a new branch that has support for the "time" datatype and am wondering if that will fix @sebyte 's problem.

**Comment by marijnh** [comment]
There'll be rows with other types that don't have a binary reader, though. Is there a way to have it fall back to the string format when encountering a 'parameterized' type where not all inner types have binary readers defined? (I don't remember how the protocol worked, I have to admit.)

**Comment by slyrus** [comment]
Well, my idea has been that we'll have binary readers for everything. Not sure if that's feasible. I think that when we read the row type, we have to decide if it's binary or text and I don't think we get the info on what the types of the row value are by then. However, it seems clear that attempting to parse a text string form from an unknown type inside a row type is the wrong thing to do. Darn.

**Comment by slyrus** [comment]
The only other thing that springs to mind is that we could go back to text format for row types (by default) and have some sort of settable *use-binary-for-row-types* that would get called when we now check field-binary-p (e.g., field-binary-p becomes nil for text, t for binary, or a function that gets called otherwise). Not the greatest, but if we can't guarantee binary readers for everything we might have to do something like this. I'd hate to go back to text everywhere for row types.

**Comment by slyrus** [comment]
@marijnh when you get a chance, check out: https://github.com/slyrus/Postmodern/tree/text-and-binary-interpreter-support

this allows for both text and binary support. If you like this, should we default to text for row types? would require updating some of the tests, but not a big deal.

**Comment by marijnh** [comment]
> Not sure if that's feasible.

I don't think it is. Plugins, or whatever they are called, can add additional types, and the standard set of types is already quite large.

Your patch looks okay, I guess, though as I said before I'm not really familiar with the code anymore.

**Comment by marijnh** [comment]
@sebyte Did #91 help?

**Comment by slyrus** [comment]
So it think text/binary row values were a red herring here. Probably good to fix anyway, but the following fails for me:

(cl-postgres::with-text-row-values
  (with-db-connection (conn)
    (cl-postgres:exec-query conn "drop table test")
    (cl-postgres:exec-query conn "create table test (a integer[])")
    (unwind-protect
         (progn
           (cl-postgres:prepare-query conn "integer-array-insert" "insert into test values ($1)")
           (cl-postgres:exec-prepared conn "integer-array-insert" (list "{{0,0},{20,22}}"))
           (cl-postgres:exec-prepared conn "integer-array-insert" (list "{{1,1}}"))
           (cl-postgres:exec-prepared conn "integer-array-insert" (list "{{2,2}, {3,4}}"))
           (cl-postgres:exec-prepared conn "integer-array-insert" (list "{{5,6}}"))
           (cl-postgres:exec-query
            conn
            "select a[2:3] from test"
            'cl-postgres:list-row-reader))
      (cl-postgres:exec-query conn "drop table test"))))

if I select a[1:3], everything is fine. So it must be something about array indices. investigating further.

**Comment by slyrus** [comment]
And... here is the ultra-reduced test case that fails:

``

(with-db-connection (conn)
    (cl-postgres:exec-query
            conn
            "select (ARRAY[1])[2:3]"
            'cl-postgres:alist-row-reader))

**Comment by slyrus** [comment]
Ok, my binary array reading code wasn't handling NULLs properly, nor was it handling zero-dimension pg arrays properly. fix coming.

**Comment by slyrus** [comment]
@sebyte can you try this: https://github.com/slyrus/Postmodern/tree/fix-null-arrays

**Comment by sebyte** [comment]
No joy.
```
Unhandled CL-POSTGRES::PROTOCOL-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {100458EC93}>:
  PostgreSQL protocol error: Unexpected message received: ^@

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {100458EC93}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<CL-POSTGRES::PROTOCOL-ERROR {1004BF2D03}> #<unavailable argument>)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<CL-POSTGRES::PROTOCOL-ERROR {1004BF2D03}>)
2: (INVOKE-DEBUGGER #<CL-POSTGRES::PROTOCOL-ERROR {1004BF2D03}>)
3: (ERROR CL-POSTGRES::PROTOCOL-ERROR :MESSAGE "Unexpected message received: ^@")
4: (CL-POSTGRES::LOOK-FOR-ROW #<unavailable argument>)
5: (CL-POSTGRES:ALIST-ROW-READER #<SB-SYS:FD-STREAM for "socket 127.0.0.1:35219, peer: 127.0.0.1:5432" {1004B2DC03}> #(#<CL-POSTGRES::FIELD-DESCRIPTION {1004BF1BA3}>))
6: (CL-POSTGRES::SEND-EXECUTE #<SB-SYS:FD-STREAM for "socket 127.0.0.1:35219, peer: 127.0.0.1:5432" {1004B2DC03}> #<unavailable argument> #<unavailable argument> #<unavailable argument>)
7: ((LABELS #:G740 :IN CL-POSTGRES:EXEC-PREPARED))
8: ((LAMBDA NIL :IN "/var/www/hunch/dom/dattdb.info/00-model/dattdb.lisp"))
```
Again, it works without the indices ([2:99]).

**Comment by slyrus** [comment]
@sebyte can you try the version on the https://github.com/slyrus/Postmodern/tree/fix-null-arrays branch and tell me if you get the error I left there for you?

@marijnh we could go back to a binary/text switch a la the row values stuff, if you would like.

**Comment by sebyte** [comment]
My mistake. Sorry. My git fu was lacking. I can't see the error you left for me because there is no error! It starts cleanly. :-)

**Comment by slyrus** [comment]
@sebyte if you're happy with the fix, would you mark this as closed? thanks!
